// ══════════════════════════════════════════════════════════════════════════════
// [JS-2] ADHAN AUDIO ENGINE — الأذان
// ══════════════════════════════════════════════════════════════════════════════
// Audio engine only. Prayer times are supplied by the unchanged prayer schedule.
var _adhanAudio=null,_adhanPlayed={},_adhanEnabled=true,_adhanDay='',_adhanPending=null,_audioUnlocked=false;
var _adhanFajrURL='https://raw.githubusercontent.com/AalianKhan/adhans/master/adhan_fajr.mp3';
var _adhanNormalURL='https://raw.githubusercontent.com/AalianKhan/adhans/master/adhan.mp3';
var _adhanFallbackURL='https://raw.githubusercontent.com/AalianKhan/adhans/master/adhan.mp3';
function adhanSetAudioURLs(normalURL,fajrURL,fallbackURL){if(typeof normalURL==='string'&&normalURL)_adhanNormalURL=normalURL;if(typeof fajrURL==='string'&&fajrURL)_adhanFajrURL=fajrURL;if(typeof fallbackURL==='string'&&fallbackURL)_adhanFallbackURL=fallbackURL;}
function adhanSetEnabled(value){_adhanEnabled=!!value;if(!_adhanEnabled){_adhanPending=null;_stopAdhanFromAlert();}return _adhanEnabled;}
function adhanIsEnabled(){return !!_adhanEnabled;}
function _startAdhanAudio(url,allowFallback){try{if(_adhanAudio){try{_adhanAudio.pause();}catch(_){}_adhanAudio=null;}_adhanAudio=new Audio(url);_adhanAudio.preload='auto';_adhanAudio.volume=1;var p=_adhanAudio.play();if(p&&typeof p.catch==='function')p.catch(function(){if(allowFallback&&url!==_adhanFallbackURL)setTimeout(function(){_startAdhanAudio(_adhanFallbackURL,false);},350);});_adhanAudio.onerror=function(){if(allowFallback&&url!==_adhanFallbackURL){_adhanAudio.onerror=null;setTimeout(function(){_startAdhanAudio(_adhanFallbackURL,false);},200);}};return true;}catch(e){if(allowFallback&&url!==_adhanFallbackURL){try{setTimeout(function(){_startAdhanAudio(_adhanFallbackURL,false);},250);}catch(_){}}return false;}}
function _playAdhan(isFajr){if(!_adhanEnabled)return;if(!_audioUnlocked){_adhanPending={isFajr:!!isFajr};try{_showAdhanAlert(isFajr?'الفجر':'الصلاة');}catch(e){}return;}_executeAdhan(isFajr);}
function _executeAdhan(isFajr){_startAdhanAudio(isFajr?_adhanFajrURL:_adhanNormalURL,true);try{navigator.vibrate([400,200,400,200,400,400,200,400,200,600]);}catch(e){}}
function _unlockAudio(){if(_audioUnlocked)return;_audioUnlocked=true;if(_adhanPending!==null){var p=_adhanPending;_adhanPending=null;_executeAdhan(p.isFajr);}}
function adhanUnlockAudio(){_unlockAudio();return _audioUnlocked;}
function _checkAdhan(now,pCache){if(!pCache||!pCache.length||!_adhanEnabled)return;var today=now.toDateString();if(_adhanDay!==today){_adhanDay=today;_adhanPlayed={};}var n=now.getHours()+now.getMinutes()/60+now.getSeconds()/3600;pCache.forEach(function(p){if(p.n==='الشروق')return;var diff=(n-p.h)*3600,key=today+'_'+p.n;if(diff>=0&&diff<30&&!_adhanPlayed[key]){_adhanPlayed[key]=true;_playAdhan(p.n==='الفجر');try{_showAdhanAlert(p.n);}catch(e){}}});}
function _stopAdhanFromAlert(){try{if(_adhanAudio){_adhanAudio.pause();_adhanAudio.currentTime=0;}}catch(e){}}
function _removeAdhanAlert(){var el=document.getElementById('adhan-alert');if(el&&el.parentNode)el.parentNode.removeChild(el);}
function _showAdhanAlert(prayerName){var el=document.getElementById('adhan-alert');if(!el){el=document.createElement('div');el.id='adhan-alert';el.setAttribute('role','alert');el.setAttribute('aria-live','assertive');el.setAttribute('aria-atomic','true');el.style.cssText=['position:fixed','top:max(12px,env(safe-area-inset-top))','left:12px','right:12px','z-index:9999','padding:14px 14px 14px 16px','background:rgba(255,253,248,.985)','border:1px solid rgba(157,120,50,.18)','border-radius:20px','box-shadow:0 16px 48px rgba(56,45,29,.18)','display:grid','grid-template-columns:44px minmax(0,1fr) auto','align-items:center','gap:12px','direction:rtl','color:#26231e','backdrop-filter:blur(16px)','-webkit-backdrop-filter:blur(16px)'].join(';');document.body.appendChild(el);}var isAdvance=String(prayerName).indexOf('اقترب وقت ')===0,cleanName=isAdvance?String(prayerName).replace('اقترب وقت ',''):prayerName;el.innerHTML=['<div aria-hidden="true" style="width:44px;height:44px;border-radius:14px;background:#eef8ef;color:#159447;display:flex;align-items:center;justify-content:center;font-size:1.15rem;border:1px solid #deeee1">◉</div>','<div style="min-width:0"><div style="font-size:.66rem;color:#817b70;font-weight:600">'+(isAdvance?'تنبيه الصلاة':'حان وقت')+'</div><div style="font-family:\'Noto Naskh Arabic\',serif;font-size:1.28rem;line-height:1.3;font-weight:800;color:#2f2b24;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+cleanName+'</div><div style="font-size:.58rem;color:#8b857b;margin-top:2px">'+(isAdvance?'اقترب موعد الصلاة':'يمكنك إيقاف الصوت أو إغلاق التنبيه')+'</div></div>','<div style="display:flex;align-items:center;gap:6px">'+(isAdvance?'':'<button type="button" data-adhan-alert-stop style="min-width:58px;height:38px;border:1px solid #d8eadc;border-radius:12px;background:#f4fbf5;color:#147b3d;font-family:inherit;font-size:.6rem;font-weight:700;cursor:pointer">إيقاف</button>')+'<button type="button" data-adhan-alert-close aria-label="إغلاق التنبيه" style="width:38px;height:38px;border:1px solid #e8e3da;border-radius:12px;background:#faf8f3;color:#746e65;font-size:1rem;cursor:pointer">×</button></div>'].join('');var stop=el.querySelector('[data-adhan-alert-stop]'),close=el.querySelector('[data-adhan-alert-close]');if(stop)stop.onclick=function(){_stopAdhanFromAlert();_removeAdhanAlert();};if(close)close.onclick=_removeAdhanAlert;setTimeout(function(){if(el&&el.parentNode)el.remove();},300000);}
function adhanToggleSound(){adhanSetEnabled(!_adhanEnabled);var btn=document.getElementById('adhan-sound-btn');if(btn)btn.textContent=_adhanEnabled?'🔊 الصوت مفعّل':'🔇 الصوت متوقف';try{navigator.vibrate(40);}catch(e){}return _adhanEnabled;}
function adhanPlayNow(isFajr){try{_audioUnlocked=true;_startAdhanAudio(isFajr?_adhanFajrURL:_adhanNormalURL,true);try{navigator.vibrate([120,70,120]);}catch(e){}}catch(err){}}
function updateHome(sp,mp,evts,now,pCache){var days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],months=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];var day=days[now.getDay()],d=now.getDate(),m=months[now.getMonth()],y=now.getFullYear();set('hm-date-greg',day+' '+d+' '+m+' '+y);try{var hd=new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(now);set('hm-date-hijri',hd+' هـ');}catch(e){set('hm-date-hijri','');}if(typeof QT!=='undefined')set('hm-qibla-deg',QT.toFixed(1)+'°');if(mp){set('hm-moon-ill',(mp.illum*100).toFixed(0)+'% إضاءة');set('hm-moon-ph',typeof phaseName==='function'?phaseName(mp.elong):'');}set('hm-gps-src',gnssSource==='gps'?'✓ GPS ±'+Math.round(gnssAccuracy||5)+'م':gnssSource==='ip'?'◎ موقع IP':'○ الموقع الافتراضي');if(pCache&&pCache.length){var n=now.getHours()+now.getMinutes()/60+now.getSeconds()/3600,ci=-1;for(var i=pCache.length-1;i>=0;i--)if(n>=pCache[i].h){ci=i;break;}var ni=(ci+1)%pCache.length,np=pCache[ni],stn=(np.h-n)*3600;if(stn<0)stn+=86400;set('hm-prayer-name',np.n);set('hm-prayer-time',typeof hm==='function'?hm(np.h):'--:--');set('hm-prayer-eta',typeof shms==='function'?shms(stn):'---');set('hm-next-p',np.n+' — '+(typeof hm==='function'?hm(np.h):'')+'  ('+(typeof shms==='function'?shms(stn):'')+')');}}
