(()=>{'use strict';
const DATA=window.QIBLAASTRO_AZKAR_DATA||{categories:[],items:{},audioPhrases:[],intervals:[]};
const $=id=>document.getElementById(id);
const app=$('azkarApp'),views={home:$('azHome'),reader:$('azReader'),audio:$('azAudio')};
let currentCat=null,index=0,counts=[],sessionItems=[],pointer=null,audioCtx=null,reminderTimer=null,reminderPlayer=null,selectedInterval=10,audioRunning=false,wakeLock=null,advanceTimer=null;
function show(name){Object.entries(views).forEach(([k,v])=>v&&v.classList.toggle('is-active',k===name));}
function categoryMeta(id){return DATA.categories.find(c=>c.id===id)||{id,title:id,theme:'neutral',icon:'•'};}
function normalizeText(s=''){return s.normalize('NFKC').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[\sـ،؛,.!؟:۝﴿﴾()\[\]{}"'’‘]+/g,'').trim();}
function orderedItems(id){const src=[...(DATA.items[id]||[])],chosen=new Map();src.forEach((item,pos)=>{const key=normalizeText(item.text||'');if(!key)return;const cur=chosen.get(key);if(!cur||(item.repeat||1)>(cur.item.repeat||1))chosen.set(key,{item,pos});});return[...chosen.values()].sort((a,b)=>{const ah=(a.item.repeat||1)>=100?1:0,bh=(b.item.repeat||1)>=100?1:0;return ah-bh||a.pos-b.pos;}).map(x=>x.item);}
function renderCategories(){const g=$('azCategoryGrid');g.innerHTML='';DATA.categories.forEach(c=>{const items=orderedItems(c.id);const b=document.createElement('button');b.type='button';b.className='az-cat';b.dataset.theme=c.theme||'neutral';b.innerHTML=`<span class="az-cat-icon" aria-hidden="true">${c.icon||'•'}</span><strong>${c.title}</strong><small>${items.length} ${items.length===1?'ذكر':'أذكار'}</small>`;b.addEventListener('click',()=>openCategory(c.id));g.appendChild(b);});}
async function acquireWakeLock(){try{if('wakeLock'in navigator&&document.visibilityState==='visible'){wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null});}}catch(e){wakeLock=null}}
async function releaseWakeLock(){try{if(wakeLock){await wakeLock.release();wakeLock=null}}catch(e){wakeLock=null}}
function resetSession(){clearTimeout(advanceTimer);advanceTimer=null;index=0;counts=[];sessionItems=[];currentCat=null;}
function openCategory(id){const items=orderedItems(id);if(!items.length)return;currentCat=id;sessionItems=items;index=0;counts=items.map(()=>0);const meta=categoryMeta(id);app.dataset.theme=meta.theme||'neutral';$('azReaderSection').textContent=meta.title;show('reader');renderDhikr();acquireWakeLock();}
function leaveReader(){releaseWakeLock();resetSession();app.dataset.theme='neutral';show('home');}
function getItems(){return sessionItems;}function getItem(){return getItems()[index]||null;}
function repeatLabel(n){if(n===1)return'مرة واحدة';if(n===2)return'مرتان';if(n>=3&&n<=10)return n+' مرات';return n+' مرة';}
function remainingFor(i=index){const item=getItems()[i];if(!item)return 0;return Math.max(0,Math.max(1,item.repeat||1)-(counts[i]||0));}
function renderDhikr(){clearTimeout(advanceTimer);advanceTimer=null;const item=getItem();if(!item)return;const items=getItems();$('azDhikrText').textContent=item.text;$('azDhikrSource').textContent=item.source||'';$('azDhikrVirtue').textContent=item.virtue||'';$('azReaderPosition').textContent=`الذكر ${index+1} من ${items.length}`;$('azReaderIndex').textContent=`الذكر ${index+1} من ${items.length}`;$('azRepeatLabel').textContent=repeatLabel(item.repeat||1);$('azCounterValue').textContent=remainingFor();requestAnimationFrame(fitDhikrText);}
function fitDhikrText(){const sc=$('azDhikrScroller'),txt=$('azDhikrText');if(!sc||!txt)return;const max=42,min=15,available=Math.max(80,sc.clientHeight-6);let size=max;txt.style.fontSize=size+'px';txt.style.lineHeight='2';sc.scrollTop=0;while(size>min&&txt.scrollHeight>available){size--;txt.style.fontSize=size+'px';if(size<32)txt.style.lineHeight='1.86';if(size<27)txt.style.lineHeight='1.7';if(size<22)txt.style.lineHeight='1.55';if(size<18)txt.style.lineHeight='1.45';}txt.style.fontSize=size+'px';sc.style.alignItems='center';sc.scrollTop=0;}
function haptic(pattern=12){try{navigator.vibrate&&navigator.vibrate(pattern)}catch(e){}}
function clickTone(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audioCtx)audioCtx=new C();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=500;g.gain.setValueAtTime(.015,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.045);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.05)}catch(e){}}
function pulse(){const c=$('azCounter');c.classList.remove('pulse');void c.offsetWidth;c.classList.add('pulse');}
function countTap(){const item=getItem();if(!item)return;const total=Math.max(1,item.repeat||1);if((counts[index]||0)>=total)return;counts[index]=(counts[index]||0)+1;$('azCounterValue').textContent=remainingFor();pulse();haptic(12);clickTone();if(counts[index]>=total){haptic([18,24,18]);advanceTimer=setTimeout(()=>{if(index<getItems().length-1){index++;renderDhikr()}},360);}}
function nav(delta){clearTimeout(advanceTimer);advanceTimer=null;const items=getItems();if(!items.length)return;const next=Math.max(0,Math.min(items.length-1,index+delta));if(next===index){haptic(5);return}index=next;renderDhikr();haptic(8);}
function onPointerDown(e){if(e.target.closest('button,select'))return;pointer={x:e.clientX,y:e.clientY,t:Date.now(),id:e.pointerId};}
function onPointerUp(e){if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,dt=Date.now()-pointer.t;pointer=null;if(Math.abs(dx)>52&&Math.abs(dx)>Math.abs(dy)*1.2){nav(dx>0?1:-1);return}if(Math.abs(dx)<22&&Math.abs(dy)<22&&dt<700)countTap();}
function setupReaderGestures(){const r=$('azReader');r.addEventListener('pointerdown',onPointerDown,{passive:true});r.addEventListener('pointerup',onPointerUp,{passive:true});r.addEventListener('pointercancel',()=>pointer=null,{passive:true});$('azCounter').addEventListener('click',e=>{e.stopPropagation();countTap()});$('azDhikrCard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();countTap()}else if(e.key==='ArrowRight')nav(1);else if(e.key==='ArrowLeft')nav(-1)});}
function phraseObjByIndex(){const s=$('azAudioPhrase'),i=Math.max(0,s.selectedIndex);const p=DATA.audioPhrases[i];return typeof p==='string'?{text:p,audio:null}:p||{text:'',audio:null};}
function stopReminderPlayer(){if(reminderPlayer){try{reminderPlayer.pause();reminderPlayer.currentTime=0}catch(e){}reminderPlayer=null}}
function playReminderOnce(){const p=phraseObjByIndex();if(!p.audio)return false;stopReminderPlayer();try{reminderPlayer=new Audio(p.audio);reminderPlayer.preload='metadata';const play=reminderPlayer.play();if(play&&play.catch)play.catch(()=>{});return true}catch(e){return false}}
function updateAudioAvailability(){const p=phraseObjByIndex(),available=!!p.audio,preview=$('azPreviewBtn'),toggle=$('azAudioToggle');if(preview){preview.disabled=!available;preview.textContent=available?'استماع':'الصوت سيضاف لاحقًا'}if(toggle){toggle.disabled=!available&&!audioRunning;toggle.classList.toggle('is-disabled',!available&&!audioRunning)}if(!audioRunning){$('azAudioState').textContent=available?'جاهز':'بانتظار التسجيل البشري'}updateSummary();}
function populateAudio(){const s=$('azAudioPhrase');s.innerHTML='';DATA.audioPhrases.forEach(p=>{const text=typeof p==='string'?p:p.text;const o=document.createElement('option');o.value=text;o.textContent=text;s.appendChild(o)});s.addEventListener('change',()=>{$('azAudioPreview').textContent=s.value;updateAudioAvailability()});$('azAudioPreview').textContent=s.value||'';const box=$('azIntervals');box.innerHTML='';DATA.intervals.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='az-interval'+(n===selectedInterval?' is-on':'');b.textContent=`${n} دقيقة`;b.addEventListener('click',()=>{selectedInterval=n;box.querySelectorAll('.az-interval').forEach(x=>x.classList.remove('is-on'));b.classList.add('is-on');updateSummary()});box.appendChild(b)});updateAudioAvailability();}
function updateSummary(){const p=phraseObjByIndex(),text=p.text||'الذكر المختار';$('azAudioSummary').textContent=p.audio?`${text} — كل ${selectedInterval} دقيقة`:`${text} — التسجيل البشري غير مضاف بعد`;}
function startReminder(){const p=phraseObjByIndex();if(audioRunning||!p.audio)return;audioRunning=true;const ms=selectedInterval*60000;clearInterval(reminderTimer);reminderTimer=setInterval(()=>{if(document.visibilityState==='visible')playReminderOnce()},ms);$('azAudioState').textContent='يعمل الآن';$('azAudioToggle').textContent='إيقاف التنبيه';$('azAudioToggle').disabled=false;$('azAudioToggle').classList.remove('is-disabled');$('azAudioToggle').classList.add('is-stop');$('azAudioToggle').closest('.az-audio-panel').querySelector('.az-audio-status').classList.add('is-running');updateSummary();haptic(15);}
function stopReminder(){audioRunning=false;clearInterval(reminderTimer);reminderTimer=null;stopReminderPlayer();$('azAudioState').textContent=phraseObjByIndex().audio?'جاهز':'بانتظار التسجيل البشري';$('azAudioToggle').textContent='بدء التنبيه';$('azAudioToggle').classList.remove('is-stop');$('azAudioToggle').closest('.az-audio-panel').querySelector('.az-audio-status').classList.remove('is-running');updateAudioAvailability();}
function openAudio(){releaseWakeLock();app.dataset.theme='neutral';show('audio')}
function init(){renderCategories();populateAudio();setupReaderGestures();$('azBackHome').addEventListener('click',leaveReader);$('azAudioEntry').addEventListener('click',openAudio);$('azAudioBack').addEventListener('click',()=>{stopReminderPlayer();show('home')});$('azPreviewBtn').addEventListener('click',playReminderOnce);$('azAudioToggle').addEventListener('click',()=>audioRunning?stopReminder():startReminder());window.addEventListener('resize',()=>{if(views.reader.classList.contains('is-active'))fitDhikrText()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&views.reader.classList.contains('is-active'))acquireWakeLock();if(document.visibilityState==='hidden')stopReminderPlayer();if(audioRunning&&document.visibilityState==='visible')updateSummary()});}
window.AzkarPage={openCategory,home:leaveReader,openAudio,startReminder,stopReminder,getState:()=>({currentCat,index,counts:[...counts],remaining:remainingFor(),audioRunning,selectedInterval,phrase:phraseObjByIndex().text||''})};init();})();