(()=>{'use strict';
const SURAHS=['الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const JUZ_STARTS=[[1,1],[2,142],[2,253],[3,93],[4,24],[4,148],[5,82],[6,111],[7,88],[8,41],[9,93],[11,6],[12,53],[15,1],[17,1],[18,75],[21,1],[23,1],[25,21],[27,56],[29,46],[33,31],[36,28],[39,32],[41,47],[46,1],[51,31],[58,1],[67,1],[78,1]];
const TOTAL_PAGES=604,$=id=>document.getElementById(id),mem=new Map();let currentSurah=0,currentAyah=1,observer=null,searchReady=false,searchIndex=[],totalLetters=0,toastTimer=null;
const arNum=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[d]);
function norm(s=''){return s.normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/[^\u0621-\u063A\u0641-\u064A0-9: ]/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
function arabicLetters(s=''){return (s.normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').match(/[\u0621-\u063A\u0641-\u064A]/g)||[]).length}
async function loadSurah(n){if(mem.has(n))return mem.get(n);const r=await fetch('../quran/'+n+'.json',{cache:'force-cache'});if(!r.ok)throw new Error('تعذر تحميل السورة');const d=await r.json();mem.set(n,d);return d}
function setTab(name){document.querySelectorAll('.qr-tabs button').forEach(b=>b.classList.toggle('is-on',b.dataset.tab===name));document.querySelectorAll('.qr-pane').forEach(p=>p.classList.toggle('is-on',p.dataset.pane===name));if(name==='khatma')renderKhatma()}
function renderSurahs(){const box=$('qrSurahList');box.innerHTML='';SURAHS.forEach((name,i)=>{const b=document.createElement('button');b.className='qr-surah';b.type='button';b.innerHTML=`<span class="qr-surah-num">${arNum(i+1)}</span><span><strong>سورة ${name}</strong><small>السورة ${arNum(i+1)} من ${arNum(114)}</small></span><b>‹</b>`;b.onclick=()=>openSurah(i+1,1);box.appendChild(b)})}
function renderJuz(){const box=$('qrJuzGrid');box.innerHTML='';JUZ_STARTS.forEach((st,i)=>{const b=document.createElement('button');b.className='qr-juz';b.type='button';b.innerHTML=`<strong>الجزء ${arNum(i+1)}</strong><small>يبدأ من سورة ${SURAHS[st[0]-1]} · الآية ${arNum(st[1])}</small>`;b.onclick=()=>openSurah(st[0],st[1]);box.appendChild(b)})}
function showHome(){if(observer){observer.disconnect();observer=null}$('qrReader').classList.remove('is-active','is-tools','is-focus');$('qrHome').classList.add('is-active');$('qrApp').classList.remove('reading');updateResume()}
function updateReaderNav(){const prev=$('qrPrevSurah'),next=$('qrNextSurah');if(!prev||!next)return;prev.disabled=currentSurah<=1;next.disabled=currentSurah>=114;$('qrPrevSurahName').textContent=currentSurah>1?'سورة '+SURAHS[currentSurah-2]:'بداية المصحف';$('qrNextSurahName').textContent=currentSurah<114?'سورة '+SURAHS[currentSurah]:'نهاية المصحف'}
function toggleReaderTools(force){const r=$('qrReader');if(!r||!r.classList.contains('is-active'))return;const on=typeof force==='boolean'?force:!r.classList.contains('is-tools');r.classList.toggle('is-tools',on)}
function showReaderToast(text='تم حفظ موضع القراءة'){const t=$('qrReaderToast');if(!t)return;t.textContent=text;t.classList.add('is-on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('is-on'),1400)}
async function openSurah(num,target=1){currentSurah=num;currentAyah=target;$('qrHome').classList.remove('is-active');$('qrReader').classList.add('is-active');$('qrReader').classList.remove('is-focus','is-tools');$('qrText').innerHTML='<div style="text-align:center;padding:70px;color:rgba(212,175,55,.55)">جاري تحميل السورة…</div>';updateReaderNav();try{const d=await loadSurah(num);renderReader(d,target)}catch(e){$('qrText').textContent='تعذر تحميل السورة من ملفات القرآن المحلية.'}}
function renderReader(d,target){$('qrReaderSurah').textContent='سورة '+d.name;$('qrReaderMeta').textContent=arNum(d.total_verses||d.verses.length)+' آية · '+(d.type==='meccan'?'مكية':'مدنية');$('qrSurahName').textContent='سورة '+d.name;$('qrBasmala').hidden=d.id===9;updateReaderNav();const box=$('qrText');box.innerHTML='';d.verses.forEach(v=>{const s=document.createElement('span');s.className='qr-ayah';s.dataset.ayah=v.id;s.id=`ayah-${d.id}-${v.id}`;s.append(document.createTextNode(v.text+' '));const n=document.createElement('span');n.className='qr-ayah-num';n.textContent=arNum(v.id);s.appendChild(n);s.append(document.createTextNode(' '));box.appendChild(s)});setupObserver();requestAnimationFrame(()=>{const t=$(`ayah-${d.id}-${target}`);if(t){t.classList.add('is-target');t.scrollIntoView({block:'center'});setTimeout(()=>t.classList.remove('is-target'),1800)}})}
function setupObserver(){if(observer)observer.disconnect();observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top-110)-Math.abs(b.boundingClientRect.top-110));if(visible[0]){document.querySelectorAll('.qr-ayah.is-current').forEach(x=>x.classList.remove('is-current'));visible[0].target.classList.add('is-current');currentAyah=Number(visible[0].target.dataset.ayah)||1}},{root:$('qrReader'),rootMargin:'-80px 0px -70% 0px',threshold:0});document.querySelectorAll('.qr-ayah').forEach(x=>observer.observe(x))}
function bookmark(){if(!currentSurah)return;const bm={s:currentSurah,a:currentAyah,n:SURAHS[currentSurah-1],at:Date.now()};localStorage.setItem('qr-bookmark',JSON.stringify(bm));updateResume();const b=$('qrReaderBookmark');if(b){const old=b.textContent;b.textContent='✓';setTimeout(()=>b.textContent=old,900)}showReaderToast(`تم حفظ سورة ${SURAHS[currentSurah-1]} · الآية ${arNum(currentAyah)}`)}
function getBm(){try{return JSON.parse(localStorage.getItem('qr-bookmark')||'null')}catch(e){return null}}
function updateResume(){const bm=getBm(),b=$('qrResume');if(bm&&bm.s){b.hidden=false;$('qrResumeText').textContent=`سورة ${bm.n||SURAHS[bm.s-1]} · الآية ${arNum(bm.a||1)}`;b.onclick=()=>openSurah(bm.s,bm.a||1)}else b.hidden=true}
async function ensureSearch(){if(searchReady)return;const st=$('qrSearchStatus');st.textContent='جاري إعداد فهرس البحث المحلي لأول مرة…';searchIndex=[];totalLetters=0;for(let i=1;i<=114;i++){const d=await loadSurah(i);d.verses.forEach(v=>{searchIndex.push({s:i,a:v.id,name:d.name,text:v.text,key:norm(v.text)});totalLetters+=arabicLetters(v.text)});if(i%10===0)st.textContent=`جاري إعداد الفهرس… ${arNum(i)} من ${arNum(114)}`;await new Promise(r=>setTimeout(r,0))}searchReady=true;st.textContent=`الفهرس جاهز · ${arNum(searchIndex.length)} آية`;renderKhatma()}
async function doSearch(){const raw=$('qrSearchInput').value.trim(),out=$('qrSearchResults'),st=$('qrSearchStatus');out.innerHTML='';if(!raw){st.textContent='اكتب كلمة أو جزءًا من آية.';return}const m=raw.match(/^\s*(\d{1,3})\s*[:：]\s*(\d{1,3})\s*$/);if(m){const s=+m[1],a=+m[2];if(s>=1&&s<=114){openSurah(s,a);return}}try{await ensureSearch()}catch(e){st.textContent='تعذر بناء فهرس البحث.';return}const q=norm(raw);if(!q){st.textContent='تعذر فهم عبارة البحث.';return}const tokens=q.split(' ').filter(Boolean);const results=searchIndex.filter(x=>tokens.every(t=>x.key.includes(t))).slice(0,80);st.textContent=results.length?`${arNum(results.length)} نتيجة معروضة${results.length===80?' كحد أقصى':''}`:'لا توجد نتائج مطابقة.';results.forEach(x=>{const b=document.createElement('button');b.className='qr-result';b.type='button';b.innerHTML=`<strong>سورة ${x.name} · الآية ${arNum(x.a)}</strong><p>${x.text}</p>`;b.onclick=()=>openSurah(x.s,x.a);out.appendChild(b)})}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function getKhatma(){let k={daily:4,pagesDone:0,today:0,date:todayKey(),started:Date.now()};try{k={...k,...JSON.parse(localStorage.getItem('qr-khatma')||'{}')}}catch(e){}if(k.date!==todayKey()){k.today=0;k.date=todayKey();saveKhatma(k)}k.daily=Math.max(1,Math.min(30,+k.daily||4));k.pagesDone=Math.max(0,Math.min(TOTAL_PAGES,+k.pagesDone||0));k.today=Math.max(0,+k.today||0);return k}
function saveKhatma(k){localStorage.setItem('qr-khatma',JSON.stringify(k))}
function monthsLabel(days){const months=days/30.4375;if(months<1)return `${arNum(days)} يومًا`;const m=Math.floor(months),d=Math.round((months-m)*30.4375);return `${arNum(days)} يومًا · نحو ${arNum(m)} شهر${d?` و${arNum(d)} يومًا`:''}`}
function renderKhatma(){const k=getKhatma(),left=Math.max(0,TOTAL_PAGES-k.pagesDone),days=left?Math.ceil(left/k.daily):0,pct=Math.min(100,k.pagesDone/TOTAL_PAGES*100);$('qrDailyPages').value=k.daily;$('qrDailyPagesOut').textContent=arNum(k.daily)+' صفحة';$('qrKhatmaPercent').textContent=arNum(Math.round(pct))+'٪';$('qrKhatmaBar').style.width=pct+'%';$('qrPagesDone').textContent=arNum(k.pagesDone);$('qrPagesLeft').textContent=arNum(left);$('qrDaysLeft').textContent=left?arNum(days):'تمت';$('qrTodayRead').textContent=arNum(k.today);$('qrPlanResult').textContent=left?`على خطة ${arNum(k.daily)} صفحة يوميًا: المدة المتوقعة ${monthsLabel(days)}.`:'أتممت صفحات الختمة المسجلة. يمكنك بدء ختمة جديدة.';$('qrKhatmaSummary').textContent=k.pagesDone?`أنجزت ${arNum(k.pagesDone)} من ${arNum(TOTAL_PAGES)} صفحة. يتغير التقدير تلقائيًا حسب تقدمك الفعلي.`:'حدد خطتك اليومية، ثم سجّل ما قرأته فعليًا.';if(totalLetters&&k.today){const avg=totalLetters/TOTAL_PAGES;$('qrCharEstimate').textContent='نحو '+arNum(Math.round(avg*k.today).toLocaleString('en-US'))+' حرف'}else $('qrCharEstimate').textContent=k.today?'يُحسب بعد تجهيز فهرس النص':'—'}
function changeRead(delta){const k=getKhatma();if(delta>0){k.today++;k.pagesDone=Math.min(TOTAL_PAGES,k.pagesDone+1)}else if(k.today>0){k.today--;k.pagesDone=Math.max(0,k.pagesDone-1)}saveKhatma(k);renderKhatma();if(!searchReady&&k.today)ensureSearch().catch(()=>{})}
function init(){renderSurahs();renderJuz();updateResume();document.querySelectorAll('.qr-tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('qrReaderBack').onclick=showHome;$('qrQuickBookmark').onclick=()=>{const bm=getBm();if(bm)openSurah(bm.s,bm.a||1)};$('qrReaderBookmark').onclick=bookmark;$('qrReadingSurface').onclick=()=>toggleReaderTools();$('qrPrevSurah').onclick=e=>{e.stopPropagation();if(currentSurah>1)openSurah(currentSurah-1,1)};$('qrNextSurah').onclick=e=>{e.stopPropagation();if(currentSurah<114)openSurah(currentSurah+1,1)};$('qrSavePlace').onclick=e=>{e.stopPropagation();bookmark()};$('qrSearchBtn').onclick=doSearch;$('qrSearchInput').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$('qrDailyPages').oninput=e=>{const k=getKhatma();k.daily=+e.target.value;saveKhatma(k);renderKhatma()};document.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>changeRead(+b.dataset.read));$('qrAppBack').onclick=()=>{if($('qrReader').classList.contains('is-active'))showHome();else history.back()};renderKhatma()}
window.QuranReader={openSurah,search:doSearch,bookmark,showHome,toggleReaderTools};init();
})();