/*
 * Mizan / QiblaAstro — safe multilingual rollout.
 * Presentation text only. No calculations, GNSS, astronomy, camera,
 * verification, prayer formulas, Quran text or dhikr source text.
 * Live compass, astronomical verification and observatory DOM are explicitly excluded.
 */
(function(root){
'use strict';
var current='ar';
var started=false;
var loading=false;
var originals=new WeakMap();
var translatedValues=new WeakMap();
var attrOriginals=new WeakMap();
var guard=false;
var ROLLOUT_VERSION='20260813-source-truth1';
var SUPPORTED=['ar','en','fr','id','ur'];
var PROTECTED_SELECTOR=[
  '#qrText','#qrBasmala','.qr-text','.qr-basmala','.qr-surah-frame','.qr-hadith','.qr-result p',
  '#azDhikrText','.az-dhikr-text','.az-dhikr-source','.az-dhikr-virtue','[data-i18n-protect]',
  '#page-compass','.page-compass','[data-page="compass"]','[data-qibla-page="compass"]',
  '#live-compass-card','#astro-body-card','#box-heading','#box-qibla','#box-diff','#compass-status-msg',
  '#manual-cal-section','#cvs','#astro-qibla-value','#astro-deviation-value',
  '[id*="astro-verification"]','[class*="astro-verification"]','#page-verification','.verification-screen',
  '[data-page*="verification"]','[data-qibla-verification]',
  '.qa-observatory','.qa-observatory *','video','canvas','[data-i18n-runtime-protect]'
].join(',');
var PACKS=[
  'js/i18n/ui-phrases.js',
  'js/i18n/home-phrases.js',
  'js/i18n/module-phrases.js',
  'js/i18n/extra-phrases.js',
  'js/i18n/prayer-phrases.js',
  'js/i18n/status-phrases.js',
  'js/i18n/general-phrases.js',
  'js/i18n/dynamic-patterns.js',
  'js/i18n/en-batch1.js',
  'js/i18n/en-safe2.js',
  'js/i18n/safe4-phrases.js',
  'js/i18n/fr-phrases.js'
];
function safeLang(v){return SUPPORTED.indexOf(v)>=0?v:'ar';}
function readSaved(){try{var raw=localStorage.getItem('qibla-cfg');if(raw){var cfg=JSON.parse(raw);if(cfg&&cfg.lang)return safeLang(cfg.lang);}}catch(_){ }try{return safeLang(localStorage.getItem('mizan-lang'));}catch(_){return'ar';}}
function save(lang){try{var cfg={},raw=localStorage.getItem('qibla-cfg');if(raw)cfg=JSON.parse(raw)||{};cfg.lang=lang;localStorage.setItem('qibla-cfg',JSON.stringify(cfg));if(root.CFG)root.CFG.lang=lang;}catch(_){ }try{localStorage.setItem('mizan-lang',lang);}catch(_){ }}
function phraseMap(lang){var out=Object.assign({},root.MIZAN_UI_PHRASES&&root.MIZAN_UI_PHRASES[lang]||{},root.MIZAN_HOME_PHRASES&&root.MIZAN_HOME_PHRASES[lang]||{},root.MIZAN_MODULE_PHRASES&&root.MIZAN_MODULE_PHRASES[lang]||{},root.MIZAN_EXTRA_PHRASES&&root.MIZAN_EXTRA_PHRASES[lang]||{},root.MIZAN_PRAYER_PHRASES&&root.MIZAN_PRAYER_PHRASES[lang]||{},root.MIZAN_STATUS_PHRASES&&root.MIZAN_STATUS_PHRASES[lang]||{},root.MIZAN_GENERAL_PHRASES&&root.MIZAN_GENERAL_PHRASES[lang]||{},root.MIZAN_SAFE4_PHRASES&&root.MIZAN_SAFE4_PHRASES[lang]||{});if(lang==='en')Object.assign(out,root.MIZAN_EN_BATCH1_PHRASES||{},root.MIZAN_EN_SAFE2_PHRASES||{});if(lang==='fr')Object.assign(out,root.MIZAN_FR_PHRASES||{});return out;}
function dynamicTranslate(core,lang){var list=[];if(root.MIZAN_DYNAMIC_PATTERNS&&root.MIZAN_DYNAMIC_PATTERNS[lang])list=list.concat(root.MIZAN_DYNAMIC_PATTERNS[lang]);if(root.MIZAN_SAFE4_DYNAMIC&&root.MIZAN_SAFE4_DYNAMIC[lang])list=list.concat(root.MIZAN_SAFE4_DYNAMIC[lang]);if(lang==='en'){if(root.MIZAN_EN_BATCH1_DYNAMIC)list=list.concat(root.MIZAN_EN_BATCH1_DYNAMIC);if(root.MIZAN_EN_SAFE2_DYNAMIC)list=list.concat(root.MIZAN_EN_SAFE2_DYNAMIC);}if(lang==='fr'&&root.MIZAN_FR_DYNAMIC)list=list.concat(root.MIZAN_FR_DYNAMIC);for(var i=0;i<list.length;i++){try{var p=list[i],re=new RegExp(p[0]);if(re.test(core))return core.replace(re,p[1]);}catch(_){ }}return null;}
function protectedNode(n){try{var el=n&&n.nodeType===1?n:n&&n.parentElement;if(!el)return false;if(/^(SCRIPT|STYLE|NOSCRIPT|CODE|PRE|TEXTAREA)$/.test(el.tagName))return true;return !!el.closest(PROTECTED_SELECTOR);}catch(_){return false;}}
function explicitSource(n){try{var el=n&&n.parentElement;if(!el||!el.getAttribute)return'';return el.getAttribute('data-mizan-i18n-source')||'';}catch(_){return'';}}
function hasArabicSource(v){return /[\u0600-\u06FF]/.test(String(v||''));}
function rememberNode(n){if(!originals.has(n)){var source=explicitSource(n);originals.set(n,source||n.nodeValue);}}
function refreshOriginalNode(n){if(!originals.has(n))return;var source=explicitSource(n);if(source){originals.set(n,source);return;}var value=n.nodeValue;if(hasArabicSource(value))originals.set(n,value);}
function restoreNode(n){if(!n||protectedNode(n))return;var source=explicitSource(n);if(source){n.nodeValue=source;originals.delete(n);}else if(originals.has(n)){n.nodeValue=originals.get(n);originals.delete(n);}translatedValues.delete(n);}
function rememberAttr(el,name){var m=attrOriginals.get(el);if(!m){m={};attrOriginals.set(el,m);}if(!(name in m))m[name]=el.getAttribute(name);}
function restoreAttrs(el){if(!el||protectedNode(el))return;var m=attrOriginals.get(el);if(!m)return;Object.keys(m).forEach(function(name){var v=m[name];if(v===null)el.removeAttribute(name);else el.setAttribute(name,v);});attrOriginals.delete(el);}
function translateTextNode(n,map,lang){if(!n||n.nodeType!==3||protectedNode(n))return;var actual=n.nodeValue,source=explicitSource(n),raw=source||actual;if(!raw||!raw.trim())return;var lead=source?'':(actual.match(/^\s*/)||[''])[0],tail=source?'':(actual.match(/\s*$/)||[''])[0],core=raw.trim();var tr=map[core]||dynamicTranslate(core,lang);if(!tr||tr===core)return;rememberNode(n);var val=lead+tr+tail;translatedValues.set(n,val);n.nodeValue=val;}
function translateAttrs(el,map,lang){if(!el||el.nodeType!==1||protectedNode(el))return;['aria-label','title','placeholder'].forEach(function(name){var v=el.getAttribute(name);if(!v)return;var core=v.trim(),tr=map[core]||dynamicTranslate(core,lang);if(tr&&tr!==core){rememberAttr(el,name);el.setAttribute(name,tr);}});}
function walk(doc,lang){if(!doc||!doc.documentElement)return;var map=phraseMap(lang);guard=true;try{var base=doc.body||doc.documentElement,w=doc.createTreeWalker(base,NodeFilter.SHOW_TEXT,null),n;while((n=w.nextNode()))translateTextNode(n,map,lang);var els=base.querySelectorAll('*');for(var i=0;i<els.length;i++)translateAttrs(els[i],map,lang);bindFrames(doc);}finally{guard=false;}}
function restore(doc){if(!doc||!doc.documentElement)return;guard=true;try{var base=doc.body||doc.documentElement,w=doc.createTreeWalker(base,NodeFilter.SHOW_TEXT,null),n;while((n=w.nextNode()))restoreNode(n);var els=base.querySelectorAll('*');for(var i=0;i<els.length;i++)restoreAttrs(els[i]);var frames=doc.querySelectorAll('iframe');for(var j=0;j<frames.length;j++){try{restore(frames[j].contentDocument);}catch(_){ }}}finally{guard=false;}}
function applySafeDirection(doc,lang){if(!doc||!doc.documentElement)return;doc.documentElement.setAttribute('lang',lang);doc.documentElement.setAttribute('data-mizan-lang',lang);doc.documentElement.setAttribute('dir','rtl');var id='mizan-safe-language-direction',style=doc.getElementById(id);if(!style){style=doc.createElement('style');style.id=id;style.textContent='html[data-mizan-lang="en"] #qa-home,html[data-mizan-lang="en"] #page-settings,html[data-mizan-lang="en"] #page-prayer,html[data-mizan-lang="en"] #page-gnss,html[data-mizan-lang="en"] #page-serenity,html[data-mizan-lang="en"] .qa-home,html[data-mizan-lang="en"] .qa-prayer-screen,html[data-mizan-lang="en"] .qr-app,html[data-mizan-lang="en"] .az-app,html[data-mizan-lang="fr"] #qa-home,html[data-mizan-lang="fr"] #page-settings,html[data-mizan-lang="fr"] #page-prayer,html[data-mizan-lang="fr"] #page-gnss,html[data-mizan-lang="fr"] #page-serenity,html[data-mizan-lang="fr"] .qa-home,html[data-mizan-lang="fr"] .qa-prayer-screen,html[data-mizan-lang="fr"] .qr-app,html[data-mizan-lang="fr"] .az-app,html[data-mizan-lang="id"] #qa-home,html[data-mizan-lang="id"] #page-settings,html[data-mizan-lang="id"] #page-prayer,html[data-mizan-lang="id"] #page-gnss,html[data-mizan-lang="id"] #page-serenity,html[data-mizan-lang="id"] .qa-home,html[data-mizan-lang="id"] .qa-prayer-screen,html[data-mizan-lang="id"] .qr-app,html[data-mizan-lang="id"] .az-app{direction:ltr!important;text-align:start} html[data-mizan-lang="ur"] #qa-home,html[data-mizan-lang="ur"] #page-settings,html[data-mizan-lang="ur"] #page-prayer,html[data-mizan-lang="ur"] #page-gnss,html[data-mizan-lang="ur"] #page-serenity,html[data-mizan-lang="ur"] .qa-home,html[data-mizan-lang="ur"] .qa-prayer-screen,html[data-mizan-lang="ur"] .qr-app,html[data-mizan-lang="ur"] .az-app{direction:rtl!important} .qr-text,.qr-basmala,#qrText,#qrBasmala,.az-dhikr-text,#azDhikrText,.az-dhikr-source,.az-dhikr-virtue,[data-i18n-protect]{direction:rtl!important}';(doc.head||doc.documentElement).appendChild(style);}}
function observe(doc){if(!doc||!doc.documentElement||doc.__mizanSafeI18nObserved)return;doc.__mizanSafeI18nObserved=true;new MutationObserver(function(muts){if(guard||current==='ar')return;var map=phraseMap(current);guard=true;try{muts.forEach(function(m){if(m.type==='characterData'){if(protectedNode(m.target))return;var own=translatedValues.get(m.target);if(own!==undefined&&own===m.target.nodeValue)return;translatedValues.delete(m.target);refreshOriginalNode(m.target);translateTextNode(m.target,map,current);}else if(m.addedNodes){for(var i=0;i<m.addedNodes.length;i++){var x=m.addedNodes[i];if(x.nodeType===3)translateTextNode(x,map,current);else if(x.nodeType===1&&!protectedNode(x)){translateAttrs(x,map,current);var w=doc.createTreeWalker(x,NodeFilter.SHOW_TEXT,null),n;while((n=w.nextNode()))translateTextNode(n,map,current);var es=x.querySelectorAll('*');for(var k=0;k<es.length;k++)translateAttrs(es[k],map,current);if(x.tagName==='IFRAME')bindFrame(x);}}}});}finally{guard=false;}}).observe(doc.documentElement,{subtree:true,childList:true,characterData:true});}
function bindFrame(frame){if(!frame||frame.__mizanSafeI18nBound)return;frame.__mizanSafeI18nBound=true;frame.addEventListener('load',function(){try{applyDocument(frame.contentDocument,current);observe(frame.contentDocument);}catch(_){ }});try{if(frame.contentDocument&&frame.contentDocument.readyState!=='loading'){applyDocument(frame.contentDocument,current);observe(frame.contentDocument);}}catch(_){ }}
function bindFrames(doc){var frames=doc.querySelectorAll('iframe');for(var i=0;i<frames.length;i++)bindFrame(frames[i]);}
function applyDocument(doc,lang){restore(doc);if(lang!=='ar')walk(doc,lang);applySafeDirection(doc,lang);if(lang==='en'&&root.MizanEnBatch1&&typeof root.MizanEnBatch1.apply==='function')try{root.MizanEnBatch1.apply(doc);}catch(_){ }}
function updateButtons(){var b=document.getElementById('qaLangToggle');if(b){var marks={ar:'AR',en:'EN',fr:'FR',id:'ID',ur:'UR'};b.setAttribute('aria-label','Language');b.innerHTML='<span class="qa-lang-globe">◎</span><b>'+(marks[current]||'AR')+'</b>';}var s=document.getElementById('mizan-en-language-select');if(s)s.value=current;}
function installPicker(){var page=document.getElementById('page-settings');if(!page||document.getElementById('mizan-en-language-section'))return;var section=document.createElement('div');section.className='settings-section';section.id='mizan-en-language-section';section.innerHTML='<h4>🌐 <span>اللغة / Language</span></h4><div class="setting-row"><div><div class="setting-label">اختر لغة التطبيق / App language</div><div class="setting-sub">العربية · English · Français · Bahasa Indonesia · اردو</div></div><select id="mizan-en-language-select" aria-label="اللغة / Language" style="max-width:190px;background:var(--panel2,#0b111b);color:var(--txt,#fff);border:1px solid var(--rim,rgba(255,255,255,.15));border-radius:10px;padding:8px 10px;font:inherit"><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option><option value="id">Bahasa Indonesia</option><option value="ur">اردو</option></select></div>';page.insertBefore(section,page.firstChild);section.querySelector('select').addEventListener('change',function(){setLanguage(this.value);});updateButtons();}
function scanUntranslated(doc){doc=doc||document;var out=[],seen={};if(!doc||!doc.documentElement)return out;var base=doc.body||doc.documentElement,w=doc.createTreeWalker(base,NodeFilter.SHOW_TEXT,null),n;while((n=w.nextNode())){if(protectedNode(n))continue;var s=(n.nodeValue||'').trim();if(s&&/[\u0600-\u06FF]/.test(s)&&!seen[s]){seen[s]=1;out.push(s);}}return out;}
function setLanguage(lang){lang=safeLang(lang);if(current!==lang){restore(document);current=lang;save(lang);}else current=lang;updateButtons();applyDocument(document,current);installPicker();updateButtons();try{root.dispatchEvent(new CustomEvent('mizan:languagechange',{detail:{lang:current}}));root.dispatchEvent(new CustomEvent('qiblaastro:language-change',{detail:{lang:current}}));}catch(_){ }return current;}
function interceptHomeToggle(){document.addEventListener('click',function(event){var t=event.target&&event.target.closest?event.target.closest('#qaLangToggle'):null;if(!t)return;event.preventDefault();event.stopPropagation();if(typeof event.stopImmediatePropagation==='function')event.stopImmediatePropagation();},true);}
function versioned(src){return src+(src.indexOf('?')>=0?'&':'?')+'v='+ROLLOUT_VERSION;}
function loadScript(src){return new Promise(function(resolve,reject){var key=src+'@'+ROLLOUT_VERSION;if(document.querySelector('script[data-mizan-safe-pack="'+key+'"]')){resolve();return;}var s=document.createElement('script');s.src=versioned(src);s.async=false;s.dataset.mizanSafePack=key;s.onload=resolve;s.onerror=reject;(document.head||document.documentElement).appendChild(s);});}
function loadPacks(){var p=Promise.resolve();PACKS.forEach(function(src){p=p.then(function(){return loadScript(src);});});return p;}
function forceFreshWorker(){if(!('serviceWorker' in navigator))return Promise.resolve(null);return navigator.serviceWorker.register('./service-worker.js?v='+ROLLOUT_VERSION,{scope:'./',updateViaCache:'none'}).then(function(reg){try{reg.update();}catch(_){ }function activate(worker){try{if(worker)worker.postMessage({type:'SKIP_WAITING'});}catch(_){ }}activate(reg.waiting);if(reg.installing)reg.installing.addEventListener('statechange',function(){if(reg.installing&&reg.installing.state==='installed')activate(reg.installing);});return reg;}).catch(function(){return null;});}
function start(){if(started||loading)return;loading=true;forceFreshWorker().then(loadPacks).then(function(){started=true;loading=false;current=readSaved();installPicker();observe(document);interceptHomeToggle();bindFrames(document);setLanguage(current);var api=Object.freeze({setLanguage:setLanguage,getLanguage:function(){return current;},supported:SUPPORTED.slice(),scanUntranslated:scanUntranslated,rolloutVersion:ROLLOUT_VERSION});root.MizanI18n=api;root.MizanEnglishI18n=api;}).catch(function(err){loading=false;try{console.error('[i18n] Safe multilingual rollout failed; Arabic remains active.',err);}catch(_){ }applySafeDirection(document,'ar');});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(typeof globalThis!=='undefined'?globalThis:window);
