/* QiblaAstro — French presentation phrases for safe screens only.
 * No compass/verification engines, Quran verses, or dhikr source text. */
(function(root){
'use strict';
root.MIZAN_FR_PHRASES=Object.freeze({
'الرئيسية':'Accueil','إعدادات':'Paramètres','الإعدادات':'Paramètres','الصلاة':'Prière','الأذكار':'Adhkar','فلكي':'Astronomie','قرآن':'Coran','اللغة':'Langue','تغيير اللغة':'Changer de langue','رجوع':'Retour','عودة':'Retour','إغلاق':'Fermer','حفظ':'Enregistrer','إلغاء':'Annuler','تفعيل':'Activer','تعطيل':'Désactiver','تشغيل':'Lecture','إيقاف':'Arrêter','التالي':'Suivant','السابق':'Précédent','بحث':'Rechercher','تحميل':'Chargement','جاري...':'Chargement…','جاري الحساب':'Calcul en cours','جاري تحديد الموقع…':'Localisation en cours…',
'القمر':'Lune','الشمس':'Soleil','متزايد':'Croissante','متناقص':'Décroissante','مرتفع':'Élevé','الارتفاع':'Altitude','السمت':'Azimut','فوق الأفق':'Au-dessus de l’horizon','تحت الأفق':'Sous l’horizon','اتجاه القبلة الحقيقي':'Direction réelle de la Qibla','دقة عالية جداً ◈':'Très haute précision ◈','دقة عالية جداً':'Très haute précision','دقة عالية':'Haute précision',
'التاريخ الهجري':'Date hégirienne','التاريخ الهجري 🌙':'Date hégirienne 🌙','التاريخ الميلادي':'Date grégorienne','التاريخ الميلادي 📅':'Date grégorienne 📅','الصلاة القادمة':'Prochaine prière','الفجر':'Fajr','الشروق':'Lever du soleil','الظهر':'Dhuhr','العصر':'Asr','المغرب':'Maghrib','العشاء':'Isha',
'علم الفلك':'Astronomie','تعلم واستكشاف':'Apprendre et explorer','منظومة الملاحة GPS ±3m':'Navigation GPS ±3 m','راحة وسكينة':'Sérénité','الاستمتاع بالقرآن المجيد':'Profiter du Saint Coran','قرآن وأناشيد هادئة':'Coran et anachids apaisants','مواقيت الصلاة والأذان':'Horaires de prière et Adhan','المواقيت والتنبيه':'Horaires et alertes','القرآن الكريم':'Le Saint Coran','حصن المسلم':'Hisn al-Muslim','114 سورة':'114 sourates',
'حالة النظام':'État du système','جميع الأنظمة تعمل بكفاءة':'Tous les systèmes fonctionnent correctement','دقة الاتجاه':'Précision de direction','آخر تحديث':'Dernière mise à jour','في انتظار GNSS':'En attente du GNSS','جاري حساب التاريخ':'Calcul de la date','جاري حساب التاريخ الهجري':'Calcul de la date hégirienne',
'الموقع':'Localisation','موقعك الحالي':'Votre position actuelle','خط العرض':'Latitude','خط الطول':'Longitude','دقة الموقع':'Précision de localisation','المنطقة الزمنية':'Fuseau horaire','مصدر الموقع':'Source de localisation','تحديث GPS':'Actualiser le GPS','موقع IP':'Localisation IP','أنظمة الملاحة العالمية':'Systèmes mondiaux de navigation','موقعك الحالي — متعدد الأنظمة':'Votre position actuelle — multi-constellation','الدقة المدمجة Multi-constellation':'Précision combinée multi-constellation',
'القبلة':'Qibla','الاتجاه الحقيقي':'Direction réelle','من الشمال الجغرافي':'Depuis le nord géographique','قراءة البوصلة المصحَّحة':'Lecture corrigée de la boussole','بعد تعويض الانحراف WMM2025':'Après correction de la déclinaison WMM2025','الانحراف المغناطيسي':'Déclinaison magnétique','القبلة من موقعك الحالي':'Qibla depuis votre position actuelle','محسوبة من إحداثياتك الحقيقية':'Calculée à partir de vos coordonnées réelles',
'مواقيت الصلاة':'Horaires de prière','موقعك الحالي':'Votre position actuelle','اضغط على الجرس لتخصيص تنبيه كل صلاة':'Touchez la cloche pour personnaliser l’alerte de chaque prière','الأذان لجميع الصلوات':'Adhan pour toutes les prières','الأذان الأساسي':'Adhan par défaut','الأذان مفعّل':'Adhan activé','نتأكد أولًا أن الهاتف يسمح للتطبيق بإخراج الصوت':'Nous vérifions d’abord que le téléphone autorise la lecture audio','إعدادات المواقيت والتفاصيل':'Réglages des horaires et détails','صيغة الفجر':'Format du Fajr','بدون تنبيه مسبق':'Sans alerte préalable','إعدادات الأذان':'Réglages de l’Adhan','منهج الفجر والعشاء':'Méthode Fajr et Isha','رابطة العالم الإسلامي':'Ligue islamique mondiale','زاوية الفجر':'Angle du Fajr','زاوية العشاء':'Angle de l’Isha','حساب العصر':'Calcul de l’Asr','شافعي (ظل مثلي)':'Shafi‘i (ombre ×1)',
'الخوارزميات':'Algorithmes','موضع الشمس':'Position du Soleil','موضع القمر':'Position de la Lune','الانكسار الجوي':'Réfraction atmosphérique','تصحيح توبوسنتري':'Correction topocentrique','الانحراف القطبي':'Mouvement polaire','الخوارزميات المستخدمة':'Algorithmes utilisés','أنظمة GNSS':'Systèmes GNSS','الانحراف القطبي — تذبذب تشاندلر':'Mouvement polaire — oscillation de Chandler','بُعد القطب':'Distance polaire','الأحداث الجيوفيزيائية وتأثيرها الحقيقي':'Événements géophysiques et impact réel','مقارنة دقة أنظمة تحديد القبلة':'Comparaison de précision des méthodes de Qibla','سمت الشمس الآن':'Azimut solaire actuel','القبلة من الشمس':'Qibla depuis le Soleil','خريطة الاتجاهات النهارية — الشمس كمرجع':'Carte des directions diurnes — Soleil comme référence','ساعة الظل':'Cadran d’ombre','القبلة النهارية':'Qibla de jour','الظهر الشمسي — لحظة الظل الأقصر':'Midi solaire — instant de l’ombre la plus courte','السماء من موقعك الآن — معلومات فلكية وتعليمية':'Le ciel depuis votre position — informations astronomiques et pédagogiques','المنزلة العربية المحسوبة':'Manzil lunaire arabe calculé','المنزلة العربية الشمسية المحسوبة':'Manzil solaire arabe calculé','تعليم يتغير حسب موقعك':'Informations adaptées à votre position','معلومة:':'Note :','الشمال':'Nord','الشرق':'Est','الجنوب':'Sud','الغرب':'Ouest',
'اللغة / Language':'Langue','اختر لغة التطبيق / App language':'Choisir la langue de l’application','استمع إلى القرآن الكريم':'Écouter le Saint Coran','مكتبتي':'Ma bibliothèque','اختر القارئ':'Choisir le réciteur','القارئ':'Réciteur','اختر الرواية':'Choisir la riwaya','اختر السورة':'Choisir la sourate','السورة':'Sourate','مشغل القرآن الكريم':'Lecteur du Coran','يُتلى الآن':'Lecture en cours','مؤقت النوم':'Minuterie de sommeil','المفضلة':'Favoris','قائمة السور':'Liste des sourates','السورة السابقة':'Sourate précédente','السورة التالية':'Sourate suivante','تشغيل أو إيقاف':'Lecture ou pause','إضافة إلى المفضلة':'Ajouter aux favoris','إزالة من المفضلة':'Retirer des favoris','بعد انتهاء السورة':'À la fin de la sourate','بعد انتهاء الوقت':'À la fin du délai',
'مصحف للقراءة والمتابعة':'Coran pour lecture et suivi','قراءة عثمانية · بحث في الآيات · ختمة وعلامات مرجعية':'Texte uthmani · recherche de versets · khatma et favoris','الأجزاء الثلاثون':'Les trente Juz','انتقال مباشر إلى بداية الجزء':'Aller directement au début du Juz','ابحث في القرآن':'Rechercher dans le Coran','بكلمة أو جزء من آية أو مرجع مباشر مثل 2:255':'Par mot, fragment de verset ou référence directe comme 2:255','اكتب ما تتذكره من الآية…':'Saisissez ce dont vous vous souvenez du verset…','حفظ الموضع':'Enregistrer la position','تم حفظ موضع القراءة':'Position de lecture enregistrée','وردك اليومي المخطط':'Lecture quotidienne planifiée','ما قرأته اليوم فعليًا':'Lecture réellement effectuée aujourd’hui','المنجز':'Terminé','المتبقي':'Restant','المدة المتوقعة':'Durée estimée',
'ورد هادئ من الأذكار والأدعية':'Une sélection paisible d’adhkar et d’invocations','أقسام الأذكار':'Sections des Adhkar','قارئ الأذكار':'Lecteur des Adhkar','الذكر 1 من 1':'Dhikr 1 sur 1','المس الشاشة للعدّ · اسحب من اليسار إلى اليمين للتالي · ومن اليمين إلى اليسار للسابق':'Touchez l’écran pour compter · balayez pour passer au suivant ou au précédent','تذكير هادئ':'Rappel discret','اختر ذكرًا قصيرًا، ثم اختر كل كم دقيقة تريد سماعه مرة واحدة.':'Choisissez un dhikr court puis l’intervalle de lecture.','الفاصل الزمني':'Intervalle','بدء التنبيه':'Démarrer le rappel','اختر الذكر والفاصل الزمني':'Choisir le dhikr et l’intervalle',
'جميع حقوق الملكية الفكرية محفوظة':'Tous les droits de propriété intellectuelle sont réservés'
});
root.MIZAN_FR_DYNAMIC=Object.freeze([
['^منذ ([0-9٠-٩]+) دقيقة$','Il y a $1 min'],['^([0-9٠-٩]+) دقيقة$','$1 minutes'],['^([0-9٠-٩]+) آية · مكية$','$1 versets · Mecquoise'],['^([0-9٠-٩]+) آية · مدنية$','$1 versets · Médinoise'],['^الارتفاع (.+) · السمت (.+)$','Altitude $1 · azimut $2'],
['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) يناير ([0-9٠-٩]+)$','$1 janvier $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) فبراير ([0-9٠-٩]+)$','$1 février $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) مارس ([0-9٠-٩]+)$','$1 mars $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) أبريل ([0-9٠-٩]+)$','$1 avril $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) مايو ([0-9٠-٩]+)$','$1 mai $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) يونيو ([0-9٠-٩]+)$','$1 juin $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) يوليو ([0-9٠-٩]+)$','$1 juillet $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) أغسطس ([0-9٠-٩]+)$','$1 août $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) سبتمبر ([0-9٠-٩]+)$','$1 septembre $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) أكتوبر ([0-9٠-٩]+)$','$1 octobre $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) نوفمبر ([0-9٠-٩]+)$','$1 novembre $2'],['^(?:الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت) ([0-9٠-٩]+) ديسمبر ([0-9٠-٩]+)$','$1 décembre $2'],
['^([0-9٠-٩]+) ذكر$','$1 dhikr'],['^([0-9٠-٩]+) أذكار$','$1 adhkar'],['^([0-9٠-٩]+) مرات$','$1 fois'],['^([0-9٠-٩]+) مرة$','$1 fois'],['^الذكر ([0-9٠-٩]+) من ([0-9٠-٩]+)$','Dhikr $1 sur $2'],['^سورة (.+) · الآية (.+) · الصفحة (.+)$','Sourate $1 · verset $2 · page $3'],['^سورة (.+) · الآية (.+)$','Sourate $1 · verset $2'],['^الجزء (.+)$','Juz $1'],['^(.+) نتيجة معروضة$','$1 résultats affichés'],['^✓ GPS ±([0-9]+)م$','✓ GPS ±$1 m']
]);
})(typeof globalThis!=='undefined'?globalThis:window);
