/* Mizan / QiblaAstro — general non-Arabic UI phrases.
 * Arabic source remains unchanged. No calculation or verification logic.
 */
(function(root){
'use strict';
root.MIZAN_GENERAL_PHRASES=Object.freeze({
  en:Object.freeze({
    /* Settings */
    '📍 الموقع':'📍 Location','دقة الموقع':'Location accuracy','🕌 القبلة':'🕌 Qibla','دقة < 0.01°':'Accuracy < 0.01°','دقة ~1-3°':'Accuracy ~1–3°','WMM2025 · يتغير ~0.08°/سنة':'WMM2025 · changes ~0.08°/year',
    '🕌 مواقيت الصلاة':'🕌 Prayer times','رابطة العالم الإسلامي':'Muslim World League','شافعي (ظل مثلي)':'Shafi‘i (one shadow length)','⚙ الخوارزميات':'⚙ Algorithms','الخوارزميات المستخدمة':'Algorithms used','أنظمة GNSS':'GNSS systems',
    'جميع حقوق الملكية الفكرية محفوظة':'All intellectual property rights reserved','يُحظر نسخ هذا البرنامج أو توزيعه أو تعديله':'Copying, distributing, or modifying this software is prohibited','أو استخدامه تجارياً بأي شكل من الأشكال':'or using it commercially in any form','دون إذن كتابي صريح من صاحب الحقوق.':'without explicit written permission from the rights holder.',

    /* Help */
    '❓ دليل الاستخدام الشامل':'❓ Complete user guide','كل ما تحتاج معرفته لاستخدام QiblaAstro باحتراف':'Everything you need to use QiblaAstro effectively','🚀 البداية السريعة':'🚀 Quick start','🧭 البوصلة':'🧭 Compass','🌙 الليل — بدون بوصلة':'🌙 Night — without a compass','☀️ المعايرة — نهاراً وليلاً وداخلياً':'☀️ Calibration — day, night and indoors','🕌 الصلاة — مواقيت دقيقة':'🕌 Prayer — accurate times','❓ أسئلة شائعة':'❓ Frequently asked questions','📚 المراجع العلمية':'📚 Scientific references','📤 مشاركة التطبيق':'📤 Share app','📋 نسخ اتجاه القبلة':'📋 Copy Qibla direction',
    'السهم الذهبي يشير للقبلة. انظر الرقم الذهبي الكبير = اتجاه القبلة بالدرجات من الشمال. الخط الأزرق المتقطع = الشمال المغناطيسي (بوصلتك).':'The golden arrow points to the Qibla. The large golden number is the Qibla bearing in degrees from north. The dashed blue line is magnetic north from your compass.',
    'استخدم القمر أو نجم القطب. التطبيق يحسب السمت الدقيق للقمر ويخبرك كم درجة وفي أي جهة القبلة منه.':'Use the Moon or Polaris. The app shows the Moon’s calculated azimuth and the Qibla direction relative to it.',
    '7 طرق لتحديد القبلة بدون أي أداة. عند الظهر الشمسي: التطبيق ينبهك والظل يشير شمالاً بدقة مطلقة.':'Seven ways to determine the Qibla without a tool. At solar noon, the app guides you using the shortest-shadow reference.',
    'مواقيت محسوبة فلكياً بنفس دقة خوارزميات الشمس. العداد يحسب الوقت المتبقي للصلاة القادمة.':'Prayer times are astronomically calculated; the countdown shows the time remaining to the next prayer.',

    /* GNSS / map */
    '🛰️ GNSS متعدد الأبراج + الانحراف القطبي':'🛰️ Multi-constellation GNSS + polar motion','GPS · GLONASS · Galileo · BeiDou والتأثيرات الجيوفيزيائية':'GPS · GLONASS · Galileo · BeiDou and geophysical effects','🛰️ أنظمة الملاحة العالمية':'🛰️ Global navigation systems','📡 موقعك الحالي — متعدد الأنظمة':'📡 Your current position — multi-system','مصدر الموقع':'Location source','دقة الموقع':'Location accuracy','القبلة من موقعك الحالي':'Qibla from your current location','محسوبة من إحداثياتك الحقيقية':'Calculated from your actual coordinates','📡 تحديث GPS':'📡 Update GPS','🌐 موقع IP':'🌐 IP location','الدقة المدمجة Multi-constellation':'Combined multi-constellation accuracy','🌍 الانحراف القطبي — تذبذب تشاندلر':'🌍 Polar motion — Chandler wobble','⚡ الأحداث الجيوفيزيائية وتأثيرها الحقيقي':'⚡ Geophysical events and their actual effect','📊 مقارنة دقة أنظمة تحديد القبلة':'📊 Qibla direction method accuracy comparison','🗺️ اتجاه القبلة المرئي':'🗺️ Visual Qibla direction','شعاع القبلة · المسافة · الانحراف البصري':'Qibla ray · distance · visual deviation','🌐 الدائرة العظمى — الطريق الأقصر':'🌐 Great circle — shortest path',

    /* Runtime/legacy display statuses */
    '✅ البوصلة والموقع يعملان':'✅ Compass and location are working','❌ الرجاء السماح بالوصول للمستشعر':'❌ Please allow sensor access','فعّل البوصلة':'Activate compass','← يسار':'← Left','يمين →':'Right →','✅ دقيق':'✅ Accurate','حان وقت':'It is time for','اضغط لإيقاف الأذان':'Tap to stop the Adhan','🔊 الصوت مفعّل':'🔊 Sound enabled','🔇 الصوت متوقف':'🔇 Sound off','الصلاة':'Prayer',
    'جاري...':'Loading…','جاري تحديد الموقع…':'Detecting location…','موقع IP':'IP location','الجيزة افتراضي':'Giza default'
  }),
  id:Object.freeze({
    '📍 الموقع':'📍 Lokasi','دقة الموقع':'Akurasi lokasi','🕌 القبلة':'🕌 Kiblat','دقة < 0.01°':'Akurasi < 0,01°','دقة ~1-3°':'Akurasi ~1–3°','WMM2025 · يتغير ~0.08°/سنة':'WMM2025 · berubah ~0,08°/tahun',
    '🕌 مواقيت الصلاة':'🕌 Waktu Salat','رابطة العالم الإسلامي':'Liga Muslim Dunia','شافعي (ظل مثلي)':'Syafi‘i (satu panjang bayangan)','⚙ الخوارزميات':'⚙ Algoritma','الخوارزميات المستخدمة':'Algoritma yang digunakan','أنظمة GNSS':'Sistem GNSS',
    'جميع حقوق الملكية الفكرية محفوظة':'Seluruh hak kekayaan intelektual dilindungi','يُحظر نسخ هذا البرنامج أو توزيعه أو تعديله':'Dilarang menyalin, mendistribusikan, atau mengubah perangkat lunak ini','أو استخدامه تجارياً بأي شكل من الأشكال':'atau menggunakannya secara komersial dalam bentuk apa pun','دون إذن كتابي صريح من صاحب الحقوق.':'tanpa izin tertulis yang tegas dari pemegang hak.',
    '❓ دليل الاستخدام الشامل':'❓ Panduan penggunaan lengkap','كل ما تحتاج معرفته لاستخدام QiblaAstro باحتراف':'Semua yang perlu Anda ketahui untuk menggunakan QiblaAstro secara efektif','🚀 البداية السريعة':'🚀 Mulai cepat','🧭 البوصلة':'🧭 Kompas','🌙 الليل — بدون بوصلة':'🌙 Malam — tanpa kompas','☀️ المعايرة — نهاراً وليلاً وداخلياً':'☀️ Kalibrasi — siang, malam, dan di dalam ruangan','🕌 الصلاة — مواقيت دقيقة':'🕌 Salat — waktu yang akurat','❓ أسئلة شائعة':'❓ Pertanyaan umum','📚 المراجع العلمية':'📚 Referensi ilmiah','📤 مشاركة التطبيق':'📤 Bagikan aplikasi','📋 نسخ اتجاه القبلة':'📋 Salin arah Kiblat',
    'السهم الذهبي يشير للقبلة. انظر الرقم الذهبي الكبير = اتجاه القبلة بالدرجات من الشمال. الخط الأزرق المتقطع = الشمال المغناطيسي (بوصلتك).':'Panah emas menunjukkan Kiblat. Angka emas besar adalah arah Kiblat dalam derajat dari utara. Garis biru putus-putus menunjukkan utara magnetik dari kompas Anda.',
    'استخدم القمر أو نجم القطب. التطبيق يحسب السمت الدقيق للقمر ويخبرك كم درجة وفي أي جهة القبلة منه.':'Gunakan Bulan atau Polaris. Aplikasi menampilkan azimut Bulan yang dihitung dan arah Kiblat relatif terhadapnya.',
    '7 طرق لتحديد القبلة بدون أي أداة. عند الظهر الشمسي: التطبيق ينبهك والظل يشير شمالاً بدقة مطلقة.':'Tujuh cara menentukan Kiblat tanpa alat. Saat tengah hari matahari, aplikasi memandu Anda menggunakan acuan bayangan terpendek.',
    'مواقيت محسوبة فلكياً بنفس دقة خوارزميات الشمس. العداد يحسب الوقت المتبقي للصلاة القادمة.':'Waktu salat dihitung secara astronomis; penghitung menunjukkan waktu tersisa hingga salat berikutnya.',
    '🛰️ GNSS متعدد الأبراج + الانحراف القطبي':'🛰️ GNSS multi-konstelasi + gerak kutub','GPS · GLONASS · Galileo · BeiDou والتأثيرات الجيوفيزيائية':'GPS · GLONASS · Galileo · BeiDou dan efek geofisika','🛰️ أنظمة الملاحة العالمية':'🛰️ Sistem navigasi global','📡 موقعك الحالي — متعدد الأنظمة':'📡 Posisi Anda saat ini — multi-sistem','مصدر الموقع':'Sumber lokasi','دقة الموقع':'Akurasi lokasi','القبلة من موقعك الحالي':'Kiblat dari lokasi Anda saat ini','محسوبة من إحداثياتك الحقيقية':'Dihitung dari koordinat aktual Anda','📡 تحديث GPS':'📡 Perbarui GPS','🌐 موقع IP':'🌐 Lokasi IP','الدقة المدمجة Multi-constellation':'Akurasi gabungan multi-konstelasi','🌍 الانحراف القطبي — تذبذب تشاندلر':'🌍 Gerak kutub — osilasi Chandler','⚡ الأحداث الجيوفيزيائية وتأثيرها الحقيقي':'⚡ Peristiwa geofisika dan dampak nyatanya','📊 مقارنة دقة أنظمة تحديد القبلة':'📊 Perbandingan akurasi metode arah Kiblat','🗺️ اتجاه القبلة المرئي':'🗺️ Arah Kiblat visual','شعاع القبلة · المسافة · الانحراف البصري':'Sinar Kiblat · jarak · penyimpangan visual','🌐 الدائرة العظمى — الطريق الأقصر':'🌐 Lingkaran besar — jalur terpendek',
    '✅ البوصلة والموقع يعملان':'✅ Kompas dan lokasi berfungsi','❌ الرجاء السماح بالوصول للمستشعر':'❌ Izinkan akses sensor','فعّل البوصلة':'Aktifkan kompas','← يسار':'← Kiri','يمين →':'Kanan →','✅ دقيق':'✅ Akurat','حان وقت':'Waktunya','اضغط لإيقاف الأذان':'Ketuk untuk menghentikan Azan','🔊 الصوت مفعّل':'🔊 Suara aktif','🔇 الصوت متوقف':'🔇 Suara mati','الصلاة':'Salat',
    'جاري...':'Memuat…','جاري تحديد الموقع…':'Mendeteksi lokasi…','موقع IP':'Lokasi IP','الجيزة افتراضي':'Giza default'
  }),
  ur:Object.freeze({
    '📍 الموقع':'📍 مقام','دقة الموقع':'مقام کی درستگی','🕌 القبلة':'🕌 قبلہ','دقة < 0.01°':'درستگی < 0.01°','دقة ~1-3°':'درستگی ~1–3°','WMM2025 · يتغير ~0.08°/سنة':'WMM2025 · تقریباً 0.08°/سال تبدیلی',
    '🕌 مواقيت الصلاة':'🕌 نماز کے اوقات','رابطة العالم الإسلامي':'مسلم ورلڈ لیگ','شافعي (ظل مثلي)':'شافعی (ایک سایہ لمبائی)','⚙ الخوارزميات':'⚙ الگورتھمز','الخوارزميات المستخدمة':'استعمال شدہ الگورتھمز','أنظمة GNSS':'GNSS نظام',
    'جميع حقوق الملكية الفكرية محفوظة':'تمام دانشورانہ ملکیت کے حقوق محفوظ ہیں','يُحظر نسخ هذا البرنامج أو توزيعه أو تعديله':'اس سافٹ ویئر کی نقل، تقسیم یا ترمیم ممنوع ہے','أو استخدامه تجارياً بأي شكل من الأشكال':'یا اسے کسی بھی شکل میں تجارتی طور پر استعمال کرنا','دون إذن كتابي صريح من صاحب الحقوق.':'حقوق کے مالک کی واضح تحریری اجازت کے بغیر۔',
    '❓ دليل الاستخدام الشامل':'❓ مکمل استعمال گائیڈ','كل ما تحتاج معرفته لاستخدام QiblaAstro باحتراف':'QiblaAstro کو مؤثر طریقے سے استعمال کرنے کے لیے ضروری معلومات','🚀 البداية السريعة':'🚀 فوری آغاز','🧭 البوصلة':'🧭 قطب نما','🌙 الليل — بدون بوصلة':'🌙 رات — قطب نما کے بغیر','☀️ المعايرة — نهاراً وليلاً وداخلياً':'☀️ کیلیبریشن — دن، رات اور اندر','🕌 الصلاة — مواقيت دقيقة':'🕌 نماز — درست اوقات','❓ أسئلة شائعة':'❓ عام سوالات','📚 المراجع العلمية':'📚 سائنسی حوالہ جات','📤 مشاركة التطبيق':'📤 ایپ شیئر کریں','📋 نسخ اتجاه القبلة':'📋 قبلہ سمت کاپی کریں',
    'السهم الذهبي يشير للقبلة. انظر الرقم الذهبي الكبير = اتجاه القبلة بالدرجات من الشمال. الخط الأزرق المتقطع = الشمال المغناطيسي (بوصلتك).':'سنہری تیر قبلہ کی طرف اشارہ کرتا ہے۔ بڑا سنہری عدد شمال سے قبلہ کی سمت کو درجات میں دکھاتا ہے۔ نیلی نقطہ دار لکیر مقناطیسی شمال ہے۔',
    'استخدم القمر أو نجم القطب. التطبيق يحسب السمت الدقيق للقمر ويخبرك كم درجة وفي أي جهة القبلة منه.':'چاند یا قطبی ستارہ استعمال کریں۔ ایپ چاند کا حساب شدہ سمت زاویہ اور اس کے نسبت قبلہ کی سمت دکھاتی ہے۔',
    '7 طرق لتحديد القبلة بدون أي أداة. عند الظهر الشمسي: التطبيق ينبهك والظل يشير شمالاً بدقة مطلقة.':'بغیر آلے کے قبلہ معلوم کرنے کے سات طریقے۔ شمسی دوپہر میں ایپ مختصر ترین سائے کے حوالے سے رہنمائی کرتی ہے۔',
    'مواقيت محسوبة فلكياً بنفس دقة خوارزميات الشمس. العداد يحسب الوقت المتبقي للصلاة القادمة.':'نماز کے اوقات فلکیاتی طور پر حساب کیے جاتے ہیں؛ کاؤنٹ ڈاؤن اگلی نماز تک باقی وقت دکھاتا ہے۔',
    '🛰️ GNSS متعدد الأبراج + الانحراف القطبي':'🛰️ متعدد سیارچہ مجموعوں والا GNSS + قطبی حرکت','GPS · GLONASS · Galileo · BeiDou والتأثيرات الجيوفيزيائية':'GPS · GLONASS · Galileo · BeiDou اور ارضی طبیعی اثرات','🛰️ أنظمة الملاحة العالمية':'🛰️ عالمی نیویگیشن نظام','📡 موقعك الحالي — متعدد الأنظمة':'📡 آپ کا موجودہ مقام — متعدد نظام','مصدر الموقع':'مقام کا ذریعہ','دقة الموقع':'مقام کی درستگی','القبلة من موقعك الحالي':'آپ کے موجودہ مقام سے قبلہ','محسوبة من إحداثياتك الحقيقية':'آپ کے اصل نقاط سے حساب شدہ','📡 تحديث GPS':'📡 GPS اپ ڈیٹ','🌐 موقع IP':'🌐 IP مقام','الدقة المدمجة Multi-constellation':'مشترکہ متعدد سیارچہ درستگی','🌍 الانحراف القطبي — تذبذب تشاندلر':'🌍 قطبی حرکت — چاندلر جھول','⚡ الأحداث الجيوفيزيائية وتأثيرها الحقيقي':'⚡ ارضی طبیعی واقعات اور حقیقی اثر','📊 مقارنة دقة أنظمة تحديد القبلة':'📊 قبلہ سمت طریقوں کی درستگی کا موازنہ','🗺️ اتجاه القبلة المرئي':'🗺️ بصری قبلہ سمت','شعاع القبلة · المسافة · الانحراف البصري':'قبلہ شعاع · فاصلہ · بصری انحراف','🌐 الدائرة العظمى — الطريق الأقصر':'🌐 عظیم دائرہ — مختصر ترین راستہ',
    '✅ البوصلة والموقع يعملان':'✅ قطب نما اور مقام کام کر رہے ہیں','❌ الرجاء السماح بالوصول للمستشعر':'❌ سینسر تک رسائی کی اجازت دیں','فعّل البوصلة':'قطب نما فعال کریں','← يسار':'← بائیں','يمين →':'دائیں →','✅ دقيق':'✅ درست','حان وقت':'وقت ہو گیا','اضغط لإيقاف الأذان':'اذان روکنے کے لیے دبائیں','🔊 الصوت مفعّل':'🔊 آواز فعال','🔇 الصوت متوقف':'🔇 آواز بند','الصلاة':'نماز',
    'جاري...':'لوڈ ہو رہا ہے…','جاري تحديد الموقع…':'مقام معلوم ہو رہا ہے…','موقع IP':'IP مقام','الجيزة افتراضي':'جیزہ طے شدہ'
  })
});
})(typeof globalThis!=='undefined'?globalThis:window);
