/* Mizan / QiblaAstro — module UI translations only. Arabic religious/source content remains untouched. */
(function(root){
'use strict';
root.MIZAN_MODULE_PHRASES=Object.freeze({
  en:Object.freeze({
    'إعادة المعايرة':'Recalibrate','تصحيح يدوي للانحراف':'Manual deviation correction','إذا كانت البوصلة منحرفة قليلاً':'If the compass is slightly offset','حرّك الشريط لترى أثر الخطأ على الهدف':'Move the slider to see how the error affects the target','فعّل':'Activate','جاري...':'Loading…',
    'موقعك الحالي':'Current location','اضغط على الجرس لتخصيص تنبيه كل صلاة':'Tap the bell to customize each prayer alert','الأذان لجميع الصلوات':'Adhan for all prayers','الأذان الأساسي':'Default Adhan','الأذان مفعّل':'Adhan enabled','نتأكد أولًا أن الهاتف يسمح للتطبيق بإخراج الصوت':'First we check that the phone allows the app to play audio','إعدادات المواقيت والتفاصيل':'Prayer settings and details','صيغة الفجر':'Fajr format','بدون تنبيه مسبق':'No advance alert','إعدادات الأذان':'Adhan settings',
    'مصحف للقراءة والمتابعة':'Quran for reading and progress','قراءة عثمانية · بحث في الآيات · ختمة وعلامات مرجعية':'Uthmani text · verse search · Khatma and bookmarks','الأجزاء الثلاثون':'The thirty Juz','انتقال مباشر إلى بداية الجزء':'Jump directly to the beginning of a Juz','ابحث في القرآن':'Search the Quran','بكلمة أو جزء من آية أو مرجع مباشر مثل 2:255':'By word, part of a verse, or direct reference such as 2:255','اكتب ما تتذكره من الآية…':'Type what you remember from the verse…','حفظ الموضع':'Save position','تم حفظ موضع القراءة':'Reading position saved','وردك اليومي المخطط':'Planned daily reading','ما قرأته اليوم فعليًا':'What you actually read today','المنجز':'Completed','المتبقي':'Remaining','المدة المتوقعة':'Estimated duration',
    'ورد هادئ من الأذكار والأدعية':'A calm daily collection of adhkar and supplications','أقسام الأذكار':'Adhkar sections','قارئ الأذكار':'Adhkar reader','الذكر 1 من 1':'Dhikr 1 of 1','المس الشاشة للعدّ · اسحب من اليسار إلى اليمين للتالي · ومن اليمين إلى اليسار للسابق':'Tap the screen to count · swipe for next or previous','تذكير هادئ':'Gentle reminder','اختر ذكرًا قصيرًا، ثم اختر كل كم دقيقة تريد سماعه مرة واحدة.':'Choose a short dhikr, then choose how often it should play once.','الفاصل الزمني':'Interval','بدء التنبيه':'Start reminder','اختر الذكر والفاصل الزمني':'Choose the dhikr and interval',
    'السماء من موقعك الآن — معلومات فلكية وتعليمية':'The sky from your location now — astronomical and educational information','جاري تحديد الموقع…':'Detecting location…','جاري الحساب':'Calculating','المنزلة العربية المحسوبة':'Calculated Arabic lunar mansion','المنزلة العربية الشمسية المحسوبة':'Calculated Arabic solar mansion','تقسيم فلكي حسابي تعليمي بأسماء المنازل العربية، بلا تنبؤات أو أحكام.':'An educational astronomical calculation using traditional Arabic mansion names, without predictions or judgments.','تعليم يتغير حسب موقعك':'Guidance that changes with your location','معلومة:':'Note:','الشمال':'North','الشرق':'East','الجنوب':'South','الغرب':'West'
  }),
  id:Object.freeze({
    'إعادة المعايرة':'Kalibrasi ulang','تصحيح يدوي للانحراف':'Koreksi penyimpangan manual','إذا كانت البوصلة منحرفة قليلاً':'Jika kompas sedikit menyimpang','حرّك الشريط لترى أثر الخطأ على الهدف':'Geser pengatur untuk melihat dampak kesalahan pada target','فعّل':'Aktifkan','جاري...':'Memuat…',
    'موقعك الحالي':'Lokasi saat ini','اضغط على الجرس لتخصيص تنبيه كل صلاة':'Ketuk lonceng untuk menyesuaikan pengingat setiap salat','الأذان لجميع الصلوات':'Azan untuk semua salat','الأذان الأساسي':'Azan default','الأذان مفعّل':'Azan aktif','نتأكد أولًا أن الهاتف يسمح للتطبيق بإخراج الصوت':'Kami memastikan terlebih dahulu bahwa ponsel mengizinkan aplikasi memutar audio','إعدادات المواقيت والتفاصيل':'Pengaturan waktu dan detail','صيغة الفجر':'Format Subuh','بدون تنبيه مسبق':'Tanpa pengingat awal','إعدادات الأذان':'Pengaturan Azan',
    'مصحف للقراءة والمتابعة':'Al-Qur’an untuk membaca dan memantau','قراءة عثمانية · بحث في الآيات · ختمة وعلامات مرجعية':'Teks Utsmani · pencarian ayat · khatam dan penanda','الأجزاء الثلاثون':'Tiga puluh Juz','انتقال مباشر إلى بداية الجزء':'Langsung ke awal Juz','ابحث في القرآن':'Cari dalam Al-Qur’an','بكلمة أو جزء من آية أو مرجع مباشر مثل 2:255':'Dengan kata, bagian ayat, atau rujukan langsung seperti 2:255','اكتب ما تتذكره من الآية…':'Ketik bagian ayat yang Anda ingat…','حفظ الموضع':'Simpan posisi','تم حفظ موضع القراءة':'Posisi bacaan tersimpan','وردك اليومي المخطط':'Target bacaan harian','ما قرأته اليوم فعليًا':'Yang benar-benar dibaca hari ini','المنجز':'Selesai','المتبقي':'Tersisa','المدة المتوقعة':'Perkiraan durasi',
    'ورد هادئ من الأذكار والأدعية':'Kumpulan zikir dan doa harian yang menenangkan','أقسام الأذكار':'Bagian Zikir','قارئ الأذكار':'Pembaca Zikir','الذكر 1 من 1':'Zikir 1 dari 1','المس الشاشة للعدّ · اسحب من اليسار إلى اليمين للتالي · ومن اليمين إلى اليسار للسابق':'Ketuk layar untuk menghitung · usap untuk berikutnya atau sebelumnya','تذكير هادئ':'Pengingat lembut','اختر ذكرًا قصيرًا، ثم اختر كل كم دقيقة تريد سماعه مرة واحدة.':'Pilih zikir singkat, lalu tentukan setiap berapa menit diputar sekali.','الفاصل الزمني':'Interval','بدء التنبيه':'Mulai pengingat','اختر الذكر والفاصل الزمني':'Pilih zikir dan interval',
    'السماء من موقعك الآن — معلومات فلكية وتعليمية':'Langit dari lokasi Anda saat ini — informasi astronomi dan edukasi','جاري تحديد الموقع…':'Mendeteksi lokasi…','جاري الحساب':'Menghitung','المنزلة العربية المحسوبة':'Manzil Arab terhitung','المنزلة العربية الشمسية المحسوبة':'Manzil Matahari Arab terhitung','تقسيم فلكي حسابي تعليمي بأسماء المنازل العربية، بلا تنبؤات أو أحكام.':'Perhitungan astronomi edukatif dengan nama manzil Arab tradisional, tanpa ramalan atau penilaian.','تعليم يتغير حسب موقعك':'Panduan yang berubah sesuai lokasi Anda','معلومة:':'Catatan:','الشمال':'Utara','الشرق':'Timur','الجنوب':'Selatan','الغرب':'Barat'
  }),
  ur:Object.freeze({
    'إعادة المعايرة':'دوبارہ کیلیبریٹ کریں','تصحيح يدوي للانحراف':'انحراف کی دستی تصحیح','إذا كانت البوصلة منحرفة قليلاً':'اگر قطب نما معمولی سا منحرف ہو','حرّك الشريط لترى أثر الخطأ على الهدف':'سلائیڈر حرکت دے کر ہدف پر خطا کا اثر دیکھیں','فعّل':'فعال کریں','جاري...':'لوڈ ہو رہا ہے…',
    'موقعك الحالي':'موجودہ مقام','اضغط على الجرس لتخصيص تنبيه كل صلاة':'ہر نماز کی یاد دہانی کے لیے گھنٹی دبائیں','الأذان لجميع الصلوات':'تمام نمازوں کے لیے اذان','الأذان الأساسي':'بنیادی اذان','الأذان مفعّل':'اذان فعال ہے','نتأكد أولًا أن الهاتف يسمح للتطبيق بإخراج الصوت':'پہلے ہم یقینی بناتے ہیں کہ فون ایپ کو آواز چلانے کی اجازت دیتا ہے','إعدادات المواقيت والتفاصيل':'اوقات اور تفصیلات کی ترتیبات','صيغة الفجر':'فجر فارمیٹ','بدون تنبيه مسبق':'پیشگی یاد دہانی نہیں','إعدادات الأذان':'اذان کی ترتیبات',
    'مصحف للقراءة والمتابعة':'مطالعہ اور پیش رفت کے لیے قرآن','قراءة عثمانية · بحث في الآيات · ختمة وعلامات مرجعية':'عثمانی متن · آیات کی تلاش · ختم اور بک مارکس','الأجزاء الثلاثون':'تیس پارے','انتقال مباشر إلى بداية الجزء':'پارے کے آغاز پر براہ راست جائیں','ابحث في القرآن':'قرآن میں تلاش کریں','بكلمة أو جزء من آية أو مرجع مباشر مثل 2:255':'لفظ، آیت کے حصے، یا 2:255 جیسے براہ راست حوالہ سے','اكتب ما تتذكره من الآية…':'آیت کا جو حصہ یاد ہے لکھیں…','حفظ الموضع':'مقام محفوظ کریں','تم حفظ موضع القراءة':'مطالعہ کا مقام محفوظ ہوگیا','وردك اليومي المخطط':'روزانہ مطالعہ کا منصوبہ','ما قرأته اليوم فعليًا':'آج حقیقتاً جو پڑھا','المنجز':'مکمل','المتبقي':'باقی','المدة المتوقعة':'متوقع مدت',
    'ورد هادئ من الأذكار والأدعية':'اذکار اور دعاؤں کا پُرسکون روزانہ مجموعہ','أقسام الأذكار':'اذکار کے حصے','قارئ الأذكار':'اذکار ریڈر','الذكر 1 من 1':'ذکر 1 از 1','المس الشاشة للعدّ · اسحب من اليسار إلى اليمين للتالي · ومن اليمين إلى اليسار للسابق':'گنتی کے لیے اسکرین دبائیں · اگلے یا پچھلے کے لیے سوائپ کریں','تذكير هادئ':'نرم یاد دہانی','اختر ذكرًا قصيرًا، ثم اختر كل كم دقيقة تريد سماعه مرة واحدة.':'ایک مختصر ذکر منتخب کریں، پھر وقفہ منتخب کریں۔','الفاصل الزمني':'وقفہ','بدء التنبيه':'یاد دہانی شروع کریں','اختر الذكر والفاصل الزمني':'ذکر اور وقفہ منتخب کریں',
    'السماء من موقعك الآن — معلومات فلكية وتعليمية':'آپ کے مقام سے موجودہ آسمان — فلکیاتی اور تعلیمی معلومات','جاري تحديد الموقع…':'مقام معلوم کیا جا رہا ہے…','جاري الحساب':'حساب جاری ہے','المنزلة العربية المحسوبة':'حساب شدہ عربی منزل','المنزلة العربية الشمسية المحسوبة':'حساب شدہ شمسی عربی منزل','تقسيم فلكي حسابي تعليمي بأسماء المنازل العربية، بلا تنبؤات أو أحكام.':'روایتی عربی منازل کے ناموں کے ساتھ تعلیمی فلکیاتی حساب، بغیر پیش گوئی یا احکام کے۔','تعليم يتغير حسب موقعك':'آپ کے مقام کے مطابق رہنمائی','معلومة:':'معلومة:','الشمال':'شمال','الشرق':'مشرق','الجنوب':'جنوب','الغرب':'مغرب'
  })
});
})(typeof globalThis!=='undefined'?globalThis:window);
