/* QiblaAstro — safe-screen multilingual completion pack.
 * Presentation text only. Compass and astronomical verification are not targeted here.
 * Quran verses and dhikr source text are never translated by this pack.
 */
(function(root){
'use strict';
root.MIZAN_SAFE4_PHRASES=Object.freeze({
  en:Object.freeze({
    'استمع إلى القرآن الكريم':'Listen to the Holy Quran','مكتبتي':'My Library','خطوات اختيار التلاوة':'Recitation selection steps','اختر القارئ':'Choose reciter','القارئ المفضل':'Preferred reciter','اختر الرواية':'Choose edition','الرواية أو نوع التلاوة':'Edition or recitation type','اختر السورة':'Choose Surah','السورة للاستماع':'Surah to listen to','القارئ':'Reciter','جاري تحميل القرّاء…':'Loading reciters…','بعد اختيار القارئ':'After choosing a reciter','السورة':'Surah','بعد اختيار الرواية':'After choosing an edition','الاستماع يحتاج اتصالًا بالإنترنت.':'Listening requires an internet connection.','مشغل القرآن الكريم':'Quran player','يُتلى الآن':'Now playing','اختر سورة للاستماع':'Choose a Surah to listen to','إضافة إلى المفضلة':'Add to favorites','السورة السابقة':'Previous Surah','تشغيل أو إيقاف':'Play or pause','السورة التالية':'Next Surah','مؤقت النوم':'Sleep timer','مؤقت':'Timer','تغيير القارئ':'Change reciter','تغيير الرواية':'Change edition','تغيير السورة':'Change Surah','قائمة السور':'Surah list','الخطوة الأولى':'Step one','ابحث باسم القارئ':'Search by reciter name','الخطوة الثانية':'Step two','اختر الرواية أو نوع التلاوة':'Choose edition or recitation type','الخطوة الثالثة':'Step three','ابحث عن سورة':'Search for a Surah','محفوظ على هذا الجهاز':'Saved on this device','المفضلة':'Favorites','استمعت مؤخرًا':'Recently played','استماع هادئ قبل النوم':'Calm listening before sleep','إيقاف عند نهاية السورة':'Stop at the end of the Surah','إلغاء المؤقت':'Cancel timer','راحة وسكينة':'Serenity','الاستمتاع بالقرآن المجيد':'Enjoy the Holy Quran','فوق الأفق':'Above the horizon','تحت الأفق':'Below the horizon','التاريخ الميلادي':'Gregorian date','التاريخ الهجري':'Hijri date'
  }),
  id:Object.freeze({
    'استمع إلى القرآن الكريم':'Dengarkan Al-Qur’an','مكتبتي':'Koleksi Saya','خطوات اختيار التلاوة':'Langkah memilih tilawah','اختر القارئ':'Pilih qari','القارئ المفضل':'Qari pilihan','اختر الرواية':'Pilih riwayat','الرواية أو نوع التلاوة':'Riwayat atau jenis tilawah','اختر السورة':'Pilih Surah','السورة للاستماع':'Surah untuk didengarkan','القارئ':'Qari','جاري تحميل القرّاء…':'Memuat daftar qari…','بعد اختيار القارئ':'Setelah memilih qari','السورة':'Surah','بعد اختيار الرواية':'Setelah memilih riwayat','الاستماع يحتاج اتصالًا بالإنترنت.':'Mendengarkan memerlukan koneksi internet.','مشغل القرآن الكريم':'Pemutar Al-Qur’an','يُتلى الآن':'Sedang diputar','اختر سورة للاستماع':'Pilih Surah untuk didengarkan','إضافة إلى المفضلة':'Tambahkan ke favorit','السورة السابقة':'Surah sebelumnya','تشغيل أو إيقاف':'Putar atau jeda','السورة التالية':'Surah berikutnya','مؤقت النوم':'Timer tidur','مؤقت':'Timer','تغيير القارئ':'Ganti qari','تغيير الرواية':'Ganti riwayat','تغيير السورة':'Ganti Surah','قائمة السور':'Daftar Surah','الخطوة الأولى':'Langkah pertama','ابحث باسم القارئ':'Cari nama qari','الخطوة الثانية':'Langkah kedua','اختر الرواية أو نوع التلاوة':'Pilih riwayat atau jenis tilawah','الخطوة الثالثة':'Langkah ketiga','ابحث عن سورة':'Cari Surah','محفوظ على هذا الجهاز':'Tersimpan di perangkat ini','المفضلة':'Favorit','استمعت مؤخرًا':'Baru didengarkan','استماع هادئ قبل النوم':'Dengarkan dengan tenang sebelum tidur','إيقاف عند نهاية السورة':'Berhenti di akhir Surah','إلغاء المؤقت':'Batalkan timer','راحة وسكينة':'Ketenangan','الاستمتاع بالقرآن المجيد':'Menikmati Al-Qur’an','فوق الأفق':'Di atas horizon','تحت الأفق':'Di bawah horizon','التاريخ الميلادي':'Tanggal Masehi','التاريخ الهجري':'Tanggal Hijriah'
  }),
  ur:Object.freeze({
    'استمع إلى القرآن الكريم':'قرآنِ کریم سنیں','مكتبتي':'میری لائبریری','خطوات اختيار التلاوة':'تلاوت کے انتخاب کے مراحل','اختر القارئ':'قاری منتخب کریں','القارئ المفضل':'پسندیدہ قاری','اختر الرواية':'روایت منتخب کریں','الرواية أو نوع التلاوة':'روایت یا تلاوت کی قسم','اختر السورة':'سورت منتخب کریں','السورة للاستماع':'سننے کے لیے سورت','القارئ':'قاری','جاري تحميل القرّاء…':'قراء کی فہرست لوڈ ہو رہی ہے…','بعد اختيار القارئ':'قاری منتخب کرنے کے بعد','السورة':'سورت','بعد اختيار الرواية':'روایت منتخب کرنے کے بعد','الاستماع يحتاج اتصالًا بالإنترنت.':'سننے کے لیے انٹرنیٹ کنکشن درکار ہے۔','مشغل القرآن الكريم':'قرآن پلیئر','يُتلى الآن':'ابھی چل رہا ہے','اختر سورة للاستماع':'سننے کے لیے سورت منتخب کریں','إضافة إلى المفضلة':'پسندیدہ میں شامل کریں','السورة السابقة':'پچھلی سورت','تشغيل أو إيقاف':'چلائیں یا روکیں','السورة التالية':'اگلی سورت','مؤقت النوم':'سلیپ ٹائمر','مؤقت':'ٹائمر','تغيير القارئ':'قاری تبدیل کریں','تغيير الرواية':'روایت تبدیل کریں','تغيير السورة':'سورت تبدیل کریں','قائمة السور':'سورتوں کی فہرست','الخطوة الأولى':'پہلا مرحلہ','ابحث باسم القارئ':'قاری کے نام سے تلاش کریں','الخطوة الثانية':'دوسرا مرحلہ','اختر الرواية أو نوع التلاوة':'روایت یا تلاوت کی قسم منتخب کریں','الخطوة الثالثة':'تیسرا مرحلہ','ابحث عن سورة':'سورت تلاش کریں','محفوظ على هذا الجهاز':'اس ڈیوائس پر محفوظ','المفضلة':'پسندیدہ','استمعت مؤخرًا':'حال ہی میں سنا','استماع هادئ قبل النوم':'سونے سے پہلے پُرسکون سماعت','إيقاف عند نهاية السورة':'سورت کے اختتام پر روکیں','إلغاء المؤقت':'ٹائمر منسوخ کریں','راحة وسكينة':'سکون','الاستمتاع بالقرآن المجيد':'قرآنِ مجید سے لطف اندوز ہوں','فوق الأفق':'افق کے اوپر','تحت الأفق':'افق کے نیچے','التاريخ الميلادي':'عیسوی تاریخ','التاريخ الهجري':'ہجری تاریخ'
  })
});
root.MIZAN_SAFE4_DYNAMIC=Object.freeze({en:Object.freeze([['^([0-9٠-٩]+) دقيقة$','$1 minutes'],['^([0-9٠-٩]+) آية · مكية$','$1 verses · Meccan'],['^([0-9٠-٩]+) آية · مدنية$','$1 verses · Medinan']]),id:Object.freeze([['^([0-9٠-٩]+) دقيقة$','$1 menit'],['^([0-9٠-٩]+) آية · مكية$','$1 ayat · Makkiyah'],['^([0-9٠-٩]+) آية · مدنية$','$1 ayat · Madaniyah']]),ur:Object.freeze([['^([0-9٠-٩]+) دقيقة$','$1 منٹ'],['^([0-9٠-٩]+) آية · مكية$','$1 آیات · مکی'],['^([0-9٠-٩]+) آية · مدنية$','$1 آیات · مدنی']])});
})(typeof globalThis!=='undefined'?globalThis:window);
