/* Mizan / QiblaAstro — non-Arabic UI phrase translations only.
 * Arabic remains the unchanged source UI and fallback.
 * No calculations, engines, GNSS, camera, astronomy or verification logic.
 */
(function(root){
'use strict';
root.MIZAN_UI_PHRASES=Object.freeze({
  en:Object.freeze({
    'الرئيسية':'Home','البوصلة':'Compass','الصلاة':'Prayer','الأذكار':'Adhkar','فلكي':'Astronomy','قرآن':'Quran','إعدادات':'Settings',
    'البوصلة الحية':'Live Compass','اضغط لتفعيل البوصلة':'Tap to activate the compass','البوصلة الفلكية':'Astronomical Compass','اضغط للتحقق':'Tap to verify',
    'القبلة الحسابية':'Computational Qibla','القبلة الفلكية':'Astronomical Qibla','بانتظار التحقق':'Awaiting verification','الانحراف':'Deviation','الانحراف الفلكي':'Astronomical Deviation','لا يوجد تحقق بعد':'No verification yet',
    'معايرة البوصلة يدوياً':'Manual Compass Calibration','إعادة ضبط + تصحيح الانحراف':'Reset + deviation correction','تحديد الموقع الجغرافي':'Detect geographic location','الانحراف عن القبلة':'Deviation from Qibla','الخطأ الزاوي':'Angular error','الانحراف عن الكعبة':'Offset from the Kaaba',
    'الصلاة القادمة':'Next Prayer','متبقي':'Remaining','مواقيت الصلاة':'Prayer Times','الأذان':'Adhan','أذان الفجر':'Fajr Adhan','تنبيه قبل الصلاة':'Alert before prayer','المؤذن':'Muezzin','تجربة الأذان':'Test Adhan','إيقاف':'Stop','اختبار صلاحية الصوت':'Audio readiness test','الشروق':'Sunrise','الغروب':'Sunset','الظهر الشمسي':'Solar noon','التاريخ الهجري':'Hijri date','طريقة الحساب':'Calculation method',
    'القرآن الكريم':'The Holy Quran','السور':'Surahs','الأجزاء':'Juz','البحث':'Search','ختمتي':'My Khatma','استكمال القراءة':'Resume reading','فهرس السور':'Surah Index','ابحث في القرآن':'Search the Quran','حفظ الموضع':'Save position','السورة السابقة':'Previous Surah','السورة التالية':'Next Surah',
    'الأذكار':'Adhkar','تنبيه الأذكار بالصوت':'Audio Dhikr Reminder','أذكار الصباح':'Morning Adhkar','أذكار المساء':'Evening Adhkar','أذكار النوم':'Before Sleep','أذكار الاستيقاظ':'Upon Waking','بعد الصلاة':'After Prayer','أدعية':'Supplications','مرة واحدة':'Once','متوقف':'Stopped',
    'القمر الآن':'Moon Now','الشمس الآن':'Sun Now','السمت':'Azimuth','الارتفاع الظاهري':'Apparent altitude','الإضاءة':'Illumination','الطلوع':'Rise','الحالة':'State','اتجاه امتداد الظل':'Shadow direction','الزوال الشمسي':'Solar noon','كيف تستدل على القبلة من السماء؟':'How can you find the Qibla from the sky?','نجم الشمال':'Polaris','من السماء إلى الملاحة الحديثة':'From the sky to modern navigation',
    'الموقع':'Location','خط العرض':'Latitude','خط الطول':'Longitude','المنطقة الزمنية':'Time zone','القبلة':'Qibla','الاتجاه الحقيقي':'True direction','من الشمال الجغرافي':'From geographic north','قراءة البوصلة المصحَّحة':'Corrected compass reading','بعد تعويض الانحراف WMM2025':'After WMM2025 declination correction','الانحراف المغناطيسي':'Magnetic declination','منهج الفجر والعشاء':'Fajr and Isha method','زاوية الفجر':'Fajr angle','زاوية العشاء':'Isha angle','حساب العصر':'Asr calculation','الخوارزميات':'Algorithms','موضع الشمس':'Sun position','موضع القمر':'Moon position','الانكسار الجوي':'Atmospheric refraction','تصحيح توبوسنتري':'Topocentric correction','الانحراف القطبي':'Polar motion',
    'اللغة':'Language','العربية':'Arabic','الإنجليزية':'English','الإندونيسية':'Indonesian','الأردية':'Urdu','اختر لغة التطبيق':'Choose app language'
  }),
  id:Object.freeze({
    'الرئيسية':'Beranda','البوصلة':'Kompas','الصلاة':'Salat','الأذكار':'Zikir','فلكي':'Astronomi','قرآن':'Al-Qur’an','إعدادات':'Pengaturan',
    'البوصلة الحية':'Kompas Langsung','اضغط لتفعيل البوصلة':'Ketuk untuk mengaktifkan kompas','البوصلة الفلكية':'Kompas Astronomis','اضغط للتحقق':'Ketuk untuk verifikasi',
    'القبلة الحسابية':'Kiblat Perhitungan','القبلة الفلكية':'Kiblat Astronomis','بانتظار التحقق':'Menunggu verifikasi','الانحراف':'Penyimpangan','الانحراف الفلكي':'Penyimpangan Astronomis','لا يوجد تحقق بعد':'Belum ada verifikasi',
    'معايرة البوصلة يدوياً':'Kalibrasi Kompas Manual','إعادة ضبط + تصحيح الانحراف':'Atur ulang + koreksi penyimpangan','تحديد الموقع الجغرافي':'Tentukan lokasi geografis','الانحراف عن القبلة':'Penyimpangan dari Kiblat','الخطأ الزاوي':'Kesalahan sudut','الانحراف عن الكعبة':'Penyimpangan dari Ka’bah',
    'الصلاة القادمة':'Salat Berikutnya','متبقي':'Tersisa','مواقيت الصلاة':'Waktu Salat','الأذان':'Azan','أذان الفجر':'Azan Subuh','تنبيه قبل الصلاة':'Pengingat sebelum salat','المؤذن':'Muazin','تجربة الأذان':'Uji Azan','إيقاف':'Hentikan','اختبار صلاحية الصوت':'Uji kesiapan audio','الشروق':'Matahari terbit','الغروب':'Matahari terbenam','الظهر الشمسي':'Tengah hari matahari','التاريخ الهجري':'Tanggal Hijriah','طريقة الحساب':'Metode perhitungan',
    'القرآن الكريم':'Al-Qur’an','السور':'Surah','الأجزاء':'Juz','البحث':'Cari','ختمتي':'Khatam Saya','استكمال القراءة':'Lanjutkan membaca','فهرس السور':'Daftar Surah','ابحث في القرآن':'Cari dalam Al-Qur’an','حفظ الموضع':'Simpan posisi','السورة السابقة':'Surah sebelumnya','السورة التالية':'Surah berikutnya',
    'الأذكار':'Zikir','تنبيه الأذكار بالصوت':'Pengingat Zikir dengan Audio','أذكار الصباح':'Zikir Pagi','أذكار المساء':'Zikir Petang','أذكار النوم':'Sebelum Tidur','أذكار الاستيقاظ':'Bangun Tidur','بعد الصلاة':'Setelah Salat','أدعية':'Doa','مرة واحدة':'Sekali','متوقف':'Berhenti',
    'القمر الآن':'Bulan Sekarang','الشمس الآن':'Matahari Sekarang','السمت':'Azimut','الارتفاع الظاهري':'Ketinggian tampak','الإضاءة':'Pencahayaan','الطلوع':'Terbit','الحالة':'Status','اتجاه امتداد الظل':'Arah bayangan','الزوال الشمسي':'Tengah hari matahari','كيف تستدل على القبلة من السماء؟':'Bagaimana menentukan Kiblat dari langit?','نجم الشمال':'Polaris','من السماء إلى الملاحة الحديثة':'Dari langit menuju navigasi modern',
    'الموقع':'Lokasi','خط العرض':'Lintang','خط الطول':'Bujur','المنطقة الزمنية':'Zona waktu','القبلة':'Kiblat','الاتجاه الحقيقي':'Arah sebenarnya','من الشمال الجغرافي':'Dari utara geografis','قراءة البوصلة المصحَّحة':'Pembacaan kompas terkoreksi','بعد تعويض الانحراف WMM2025':'Setelah koreksi deklinasi WMM2025','الانحراف المغناطيسي':'Deklinasi magnetik','منهج الفجر والعشاء':'Metode Subuh dan Isya','زاوية الفجر':'Sudut Subuh','زاوية العشاء':'Sudut Isya','حساب العصر':'Perhitungan Asar','الخوارزميات':'Algoritma','موضع الشمس':'Posisi Matahari','موضع القمر':'Posisi Bulan','الانكسار الجوي':'Refraksi atmosfer','تصحيح توبوسنتري':'Koreksi toposentrik','الانحراف القطبي':'Gerak kutub',
    'اللغة':'Bahasa','العربية':'Arab','الإنجليزية':'Inggris','الإندونيسية':'Indonesia','الأردية':'Urdu','اختر لغة التطبيق':'Pilih bahasa aplikasi'
  }),
  ur:Object.freeze({
    'الرئيسية':'ہوم','البوصلة':'قطب نما','الصلاة':'نماز','الأذكار':'اذکار','فلكي':'فلکیات','قرآن':'قرآن','إعدادات':'ترتیبات',
    'البوصلة الحية':'براہِ راست قطب نما','اضغط لتفعيل البوصلة':'قطب نما فعال کرنے کے لیے دبائیں','البوصلة الفلكية':'فلکیاتی قطب نما','اضغط للتحقق':'تصدیق کے لیے دبائیں',
    'القبلة الحسابية':'حسابی قبلہ','القبلة الفلكية':'فلکیاتی قبلہ','بانتظار التحقق':'تصدیق کا انتظار ہے','الانحراف':'انحراف','الانحراف الفلكي':'فلکیاتی انحراف','لا يوجد تحقق بعد':'ابھی کوئی تصدیق نہیں',
    'معايرة البوصلة يدوياً':'قطب نما کی دستی کیلیبریشن','إعادة ضبط + تصحيح الانحراف':'ری سیٹ + انحراف کی درستی','تحديد الموقع الجغرافي':'جغرافیائی مقام معلوم کریں','الانحراف عن القبلة':'قبلہ سے انحراف','الخطأ الزاوي':'زاویائی خطا','الانحراف عن الكعبة':'کعبہ سے فاصلہ',
    'الصلاة القادمة':'اگلی نماز','متبقي':'باقی','مواقيت الصلاة':'نماز کے اوقات','الأذان':'اذان','أذان الفجر':'فجر کی اذان','تنبيه قبل الصلاة':'نماز سے پہلے یاد دہانی','المؤذن':'مؤذن','تجربة الأذان':'اذان آزمائیں','إيقاف':'روکیں','اختبار صلاحية الصوت':'آڈیو تیاری کا ٹیسٹ','الشروق':'طلوعِ آفتاب','الغروب':'غروبِ آفتاب','الظهر الشمسي':'شمسی دوپہر','التاريخ الهجري':'ہجری تاریخ','طريقة الحساب':'حساب کا طریقہ',
    'القرآن الكريم':'قرآنِ کریم','السور':'سورتیں','الأجزاء':'پارے','البحث':'تلاش','ختمتي':'میرا ختم','استكمال القراءة':'پڑھنا جاری رکھیں','فهرس السور':'سورتوں کی فہرست','ابحث في القرآن':'قرآن میں تلاش کریں','حفظ الموضع':'مقام محفوظ کریں','السورة السابقة':'پچھلی سورت','السورة التالية':'اگلی سورت',
    'الأذكار':'اذکار','تنبيه الأذكار بالصوت':'صوتی ذکر یاد دہانی','أذكار الصباح':'صبح کے اذکار','أذكار المساء':'شام کے اذکار','أذكار النوم':'سونے کے اذکار','أذكار الاستيقاظ':'جاگنے کے اذکار','بعد الصلاة':'نماز کے بعد','أدعية':'دعائیں','مرة واحدة':'ایک بار','متوقف':'بند',
    'القمر الآن':'چاند ابھی','الشمس الآن':'سورج ابھی','السمت':'سمت','الارتفاع الظاهري':'ظاہری ارتفاع','الإضاءة':'روشنی','الطلوع':'طلوع','الحالة':'حالت','اتجاه امتداد الظل':'سائے کی سمت','الزوال الشمسي':'شمسی دوپہر','كيف تستدل على القبلة من السماء؟':'آسمان سے قبلہ کیسے معلوم کریں؟','نجم الشمال':'قطبی ستارہ','من السماء إلى الملاحة الحديثة':'آسمان سے جدید نیویگیشن تک',
    'الموقع':'مقام','خط العرض':'عرض البلد','خط الطول':'طول البلد','المنطقة الزمنية':'ٹائم زون','القبلة':'قبلہ','الاتجاه الحقيقي':'حقیقی سمت','من الشمال الجغرافي':'جغرافیائی شمال سے','قراءة البوصلة المصحَّحة':'درست شدہ قطب نما ریڈنگ','بعد تعويض الانحراف WMM2025':'WMM2025 انحراف کی تصحیح کے بعد','الانحراف المغناطيسي':'مقناطیسی انحراف','منهج الفجر والعشاء':'فجر و عشاء کا طریقہ','زاوية الفجر':'فجر زاویہ','زاوية العشاء':'عشاء زاویہ','حساب العصر':'عصر کا حساب','الخوارزميات':'الگورتھمز','موضع الشمس':'سورج کی پوزیشن','موضع القمر':'چاند کی پوزیشن','الانكسار الجوي':'فضائی انعطاف','تصحيح توبوسنتري':'ٹوپو سینٹرک تصحیح','الانحراف القطبي':'قطبی حرکت',
    'اللغة':'زبان','العربية':'عربی','الإنجليزية':'انگریزی','الإندونيسية':'انڈونیشی','الأردية':'اردو','اختر لغة التطبيق':'ایپ کی زبان منتخب کریں'
  })
});
})(typeof globalThis!=='undefined'?globalThis:window);
