/* QiblaAstro — Adhan presentation + scheduling preferences adapter
 * Does not calculate prayer times; it only decides how existing prayer times notify.
 * © 2026 محمد سيد جبر بحيرى — Mohamed SG Behairy. All Rights Reserved.
 */
(function(root){'use strict';
var PREF_KEY='qiblaastro-adhan-ui-v5',LEGACY_KEYS=['qiblaastro-adhan-ui-v4','qiblaastro-adhan-ui-v3','qiblaastro-adhan-ui-v2','qiblaastro-adhan-ui-v1'];
var state={profile:'makkah',advance:0,enabled:true,prayers:{'الفجر':'adhan','الظهر':'adhan','العصر':'adhan','المغرب':'adhan','العشاء':'adhan'}};
var prayerLabels={adhan:'أذان كامل',notification:'إشعار فقط',off:'بدون تنبيه'};
/* Local deterministic audio only. Keep IDs stable for previously saved preferences. */
var profiles={
  makkah:{label:'الأذان الأساسي',sub:'صوت مكة',normal:'audio/adhan/mecca.mp3',fajr:'audio/adhan/fajr-alafasy.mp3'},
  calm:{label:'أذان أحمد النفيس',sub:'أحمد النفيس',normal:'audio/adhan/ahmed-al-nufais.mp3',fajr:'audio/adhan/fajr-alafasy.mp3'},
  deep:{label:'أذان إسلام صبحي',sub:'إسلام صبحي',normal:'audio/adhan/islam-sobhi.mp3',fajr:'audio/adhan/fajr-alafasy.mp3'}
};
var schedulerInstalled=false,preAlertPlayed={},lastFocus=null,backAction=null,keyBound=false;
function parseStored(){var keys=[PREF_KEY].concat(LEGACY_KEYS);for(var i=0;i<keys.length;i++){try{var raw=root.localStorage.getItem(keys[i]);if(raw){var p=JSON.parse(raw);if(p&&typeof p==='object')return {value:p,key:keys[i]};}}catch(e){}}return null;}
function read(){var found=parseStored();if(!found)return;var p=found.value;if(profiles[p.profile])state.profile=p.profile;if(Number.isFinite(+p.advance)&&[0,5,10,15].indexOf(+p.advance)>=0)state.advance=+p.advance;if(typeof p.enabled==='boolean')state.enabled=p.enabled;if(p.prayers)Object.keys(state.prayers).forEach(function(k){if(prayerLabels[p.prayers[k]])state.prayers[k]=p.prayers[k];});if(found.key!==PREF_KEY)persist();}
function persist(){try{root.localStorage.setItem(PREF_KEY,JSON.stringify(state));LEGACY_KEYS.forEach(function(k){try{root.localStorage.removeItem(k);}catch(e){}});}catch(e){}}
function announce(text){var el=document.getElementById('qa-adhan-live-status');if(!el)return;el.textContent='';root.setTimeout(function(){el.textContent=text||'';},20);}
function applyProfile(){var p=profiles[state.profile]||profiles.makkah;try{if(typeof adhanSetAudioURLs==='function')adhanSetAudioURLs(p.normal,p.fajr,profiles.makkah.normal);}catch(e){}}
function applyEnabled(){try{if(typeof adhanSetEnabled==='function')adhanSetEnabled(state.enabled);else if(typeof _adhanEnabled!=='undefined')_adhanEnabled=!!state.enabled;}catch(e){}}
function save(){persist();applyProfile();applyEnabled();}
function enabled(){return !!state.enabled;}
function unlock(){try{if(typeof adhanUnlockAudio==='function')adhanUnlockAudio();else if(typeof _unlockAudio==='function')_unlockAudio();}catch(e){}}
function preview(fajr){try{applyProfile();unlock();if(root.QiblaPrayerAudioFinalizer&&typeof root.QiblaPrayerAudioFinalizer.preview==='function')root.QiblaPrayerAudioFinalizer.preview(!!fajr);else if(typeof adhanPlayNow==='function')adhanPlayNow(!!fajr);announce(fajr?'يتم الآن تشغيل تجربة أذان الفجر':'يتم الآن تشغيل تجربة '+(profiles[state.profile]||profiles.makkah).label);}catch(e){announce('تعذر تشغيل تجربة الأذان');}}
function stopPreview(){try{if(root.QiblaPrayerAudioFinalizer&&root.QiblaPrayerAudioFinalizer.stop)return root.QiblaPrayerAudioFinalizer.stop();if(typeof _adhanAudio!=='undefined'&&_adhanAudio){_adhanAudio.pause();_adhanAudio.currentTime=0;}}catch(e){}announce('تم إيقاف الصوت');}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c];});}
function summary(){var vals=Object.keys(state.prayers).map(function(k){return state.prayers[k];});if(vals.every(function(v){return v==='adhan';}))return 'الأذان لجميع الصلوات';if(vals.every(function(v){return v==='off';}))return 'التنبيهات متوقفة';return 'إعداد مخصص لكل صلاة';}
function sync(el){if(!el)return;var master=el.querySelector('[data-qa-adhan-toggle]'),on=enabled();if(master){master.textContent=on?'الأذان مفعّل':'الأذان متوقف';master.classList.toggle('off',!on);master.setAttribute('aria-pressed',on?'true':'false');}var n=el.querySelector('#qa-notification-summary');if(n)n.textContent=summary();var a=el.querySelector('#qa-advance-summary');if(a)a.textContent=state.advance?('قبل الصلاة بـ '+state.advance+' دقائق'):'بدون تنبيه مسبق';var m=el.querySelector('#qa-muezzin-summary');if(m)m.textContent=(profiles[state.profile]||profiles.makkah).label;}
function close(){var s=document.getElementById('qa-adhan-sheet'),b=document.getElementById('qa-sheet-backdrop'),back=document.querySelector('[data-qa-back-sheet]');if(s)s.hidden=true;if(b)b.hidden=true;if(back)back.hidden=true;backAction=null;document.documentElement.style.overflow='';try{if(lastFocus&&typeof lastFocus.focus==='function')lastFocus.focus({preventScroll:true});}catch(e){}lastFocus=null;}
function option(label,sub,selected,attrs,disabled){return '<button class="qa-sheet-option'+(selected?' selected':'')+'" type="button" role="radio" aria-checked="'+(selected?'true':'false')+'" '+attrs+(disabled?' disabled aria-disabled="true"':'')+'><span><b>'+esc(label)+'</b>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</span><i class="qa-radio" aria-hidden="true"></i></button>';}
function setBack(action){var back=document.querySelector('[data-qa-back-sheet]');backAction=typeof action==='function'?action:null;if(!back)return;back.hidden=!backAction;back.onclick=function(){if(backAction)backAction();};}
function showSheet(titleText,subtitle,html,onBack){var sheet=document.getElementById('qa-adhan-sheet'),backdrop=document.getElementById('qa-sheet-backdrop'),body=document.getElementById('qa-sheet-body'),title=document.getElementById('qa-sheet-title'),sub=document.getElementById('qa-sheet-subtitle');if(!sheet||!body)return null;if(sheet.hidden)lastFocus=document.activeElement;title.textContent=titleText;sub.textContent=subtitle||'';body.innerHTML=html;setBack(onBack);sheet.hidden=false;backdrop.hidden=false;document.documentElement.style.overflow='hidden';root.requestAnimationFrame(function(){var target=document.querySelector('[data-qa-back-sheet]:not([hidden])')||body.querySelector('button:not([disabled])')||document.querySelector('[data-qa-close-sheet]');if(target)try{target.focus({preventScroll:true});}catch(e){}});return body;}
function requestNotificationPermission(){try{if(!('Notification'in root))return Promise.resolve('unsupported');if(Notification.permission==='granted')return Promise.resolve('granted');if(Notification.permission==='denied')return Promise.resolve('denied');return Notification.requestPermission();}catch(e){return Promise.resolve('error');}}
function requestAndReportPermission(){return requestNotificationPermission().then(function(result){announce(result==='granted'?'تم تفعيل إذن الإشعارات':result==='denied'?'الإشعارات محظورة من إعدادات المتصفح':result==='unsupported'?'إشعارات النظام غير مدعومة على هذا المتصفح':'تعذر تغيير إذن الإشعارات');return result;});}
function systemNotify(title,body){try{if('Notification'in root&&Notification.permission==='granted')new Notification(title,{body:body,icon:'icons/icon-192x192.png',tag:'qiblaastro-prayer'});}catch(e){}}
function navRow(name,label){return '<button class="qa-sheet-option qa-sheet-nav" type="button" data-prayer-open="'+esc(name)+'"><span><b>'+esc(name)+'</b><small>'+esc(label)+'</small></span><span class="qa-sheet-arrow" aria-hidden="true"></span></button>';}
function open(kind){var body;if(kind==='muezzin')body=showSheet('اختيار صوت الأذان','اختر أحد الأصوات المحلية ثم جرّبه',Object.keys(profiles).map(function(k){var p=profiles[k];return option(p.label,p.sub,state.profile===k,'data-profile="'+k+'"');}).join('')+'<button class="qa-sheet-test" type="button" data-test-normal>▶ تجربة الصوت المختار</button><div class="qa-sheet-note">كل مؤذن يستخدم ملفًا محليًا مختلفًا محفوظًا داخل التطبيق. أثناء التجربة لا يتم استبدال المؤذن المختار بصوت آخر.</div>');else if(kind==='fajr')body=showSheet('أذان الفجر','موعد الفجر لا يتغير بهذا الاختيار',option('صيغة أذان الفجر','ملف أذان فجر مستقل',true,'data-fajr-choice="1"')+'<button class="qa-sheet-test" type="button" data-test-fajr>▶ تجربة أذان الفجر</button><div class="qa-sheet-note">هذا الاختيار يخص الصوت فقط؛ وقت الفجر يأتي من جدول المواقيت.</div>');else if(kind==='advance')body=showSheet('التنبيه قبل الصلاة','اختر توقيت التنبيه المسبق',[0,5,10,15].map(function(v){return option(v?('قبل الصلاة بـ '+v+' دقائق'):'بدون تنبيه مسبق','',state.advance===v,'data-advance="'+v+'"');}).join('')+'<div class="qa-sheet-note">عند اختيار تنبيه مسبق سنطلب إذن الإشعارات إذا كان المتصفح يدعم ذلك.</div>');else body=showSheet('تنبيهات الصلوات','اختر صلاة لتحديد نوع التنبيه',Object.keys(state.prayers).map(function(k){return navRow(k,prayerLabels[state.prayers[k]]);}).join(''));if(body)bindSheet(body);}
function openPrayer(name){if(!state.prayers[name])return;var body=showSheet('تنبيه '+name,'اختر ما يحدث عند دخول وقت الصلاة',['adhan','notification','off'].map(function(mode){return option(prayerLabels[mode],mode==='adhan'?'تشغيل صوت الأذان':mode==='notification'?'إشعار بدون صوت أذان':'لن يصدر تنبيه',state.prayers[name]===mode,'data-prayer-mode="'+mode+'" data-prayer-name="'+esc(name)+'"');}).join(''),function(){open('notifications');});if(body)bindSheet(body);}
function bindSheet(body){body.querySelectorAll('[data-profile]').forEach(function(x){x.onclick=function(){state.profile=x.dataset.profile;save();sync(document.getElementById('qa-adhan-card'));announce('تم اختيار '+profiles[state.profile].label);open('muezzin');};});body.querySelectorAll('[data-advance]').forEach(function(x){x.onclick=function(){state.advance=+x.dataset.advance;save();sync(document.getElementById('qa-adhan-card'));announce(state.advance?'تم ضبط التنبيه قبل الصلاة بـ '+state.advance+' دقائق':'تم إلغاء التنبيه المسبق');if(state.advance>0)requestAndReportPermission();close();};});body.querySelectorAll('[data-prayer-open]').forEach(function(x){x.onclick=function(){openPrayer(x.dataset.prayerOpen);};});body.querySelectorAll('[data-prayer-mode]').forEach(function(x){x.onclick=function(){var n=x.dataset.prayerName,m=x.dataset.prayerMode;if(state.prayers[n]&&prayerLabels[m]){state.prayers[n]=m;save();sync(document.getElementById('qa-adhan-card'));announce('تم ضبط '+n+' على '+prayerLabels[m]);if(m==='notification')requestAndReportPermission();if(root.QiblaPrayerScreen)root.QiblaPrayerScreen.render();open('notifications');}};});var t=body.querySelector('[data-test-normal]');if(t)t.onclick=function(){preview(false);};var f=body.querySelector('[data-test-fajr]');if(f)f.onclick=function(){preview(true);};}
function showVisualAlert(name,prefix){try{if(typeof _showAdhanAlert==='function')_showAdhanAlert((prefix||'')+name);}catch(e){}}
function notifyPrayer(name,prefix){showVisualAlert(name,prefix);systemNotify(prefix?prefix+name:'حان وقت '+name,prefix?'اقترب موعد الصلاة':'QiblaAstro — مواقيت الصلاة');}
function installSchedulerAdapter(){if(schedulerInstalled||typeof root._checkAdhan!=='function')return;schedulerInstalled=true;root._checkAdhan=function(now,cache){if(!cache||!cache.length||!enabled())return;applyProfile();var today=now.toDateString();try{if(typeof _adhanDay!=='undefined'&&_adhanDay!==today){_adhanDay=today;_adhanPlayed={};preAlertPlayed={};}}catch(e){}var n=now.getHours()+now.getMinutes()/60+now.getSeconds()/3600;cache.forEach(function(p){if(!p||p.n==='الشروق')return;var mode=state.prayers[p.n]||'adhan',diff=(n-p.h)*3600,key=today+'_'+p.n;if(diff>=0&&diff<30){try{if(typeof _adhanPlayed!=='undefined'&&_adhanPlayed[key])return;_adhanPlayed[key]=true;}catch(e){}if(mode==='adhan'){try{if(typeof _playAdhan==='function')_playAdhan(p.n==='الفجر');}catch(e){}notifyPrayer(p.n,'');}else if(mode==='notification')notifyPrayer(p.n,'');return;}if(state.advance>0&&mode!=='off'){var before=-diff,lead=state.advance*60,preKey=today+'_pre_'+p.n+'_'+state.advance;if(before>=lead&&before<lead+30&&!preAlertPlayed[preKey]){preAlertPlayed[preKey]=true;notifyPrayer(p.n,'اقترب وقت ');}}});};}
function trapFocus(e){var s=document.getElementById('qa-adhan-sheet');if(!s||s.hidden||e.key!=='Tab')return;var items=[].slice.call(s.querySelectorAll('button:not([disabled]):not([hidden]),[href],[tabindex]:not([tabindex="-1"])')).filter(function(el){return el.offsetParent!==null;});if(!items.length)return;var first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
function bind(el){if(!el||el.dataset.qaAdhanBound==='1')return;el.dataset.qaAdhanBound='1';applyProfile();applyEnabled();installSchedulerAdapter();var master=el.querySelector('[data-qa-adhan-toggle]');if(master)master.onclick=function(){unlock();state.enabled=!state.enabled;save();sync(el);announce(enabled()?'تم تفعيل الأذان':'تم إيقاف الأذان');};el.querySelectorAll('[data-qa-open]').forEach(function(x){x.onclick=function(){unlock();open(x.dataset.qaOpen);};});var p=el.querySelector('[data-qa-adhan-preview]');if(p)p.onclick=function(){preview(false);};var sp=el.querySelector('[data-qa-stop-preview]');if(sp)sp.onclick=stopPreview;var c=document.querySelector('[data-qa-close-sheet]'),b=document.getElementById('qa-sheet-backdrop');if(c)c.onclick=close;if(b)b.onclick=close;if(!keyBound){keyBound=true;document.addEventListener('keydown',function(e){var s=document.getElementById('qa-adhan-sheet');if(e.key==='Escape'&&s&&!s.hidden){e.preventDefault();close();return;}trapFocus(e);});}sync(el);}
read();applyProfile();applyEnabled();root.QiblaAdhanUI=Object.freeze({bind:bind,sync:sync,preview:preview,open:open,openPrayer:openPrayer,getPrayerMode:function(n){return state.prayers[n]||'off';},getState:function(){return JSON.parse(JSON.stringify(state));},getProfiles:function(){return JSON.parse(JSON.stringify(profiles));},installSchedulerAdapter:installSchedulerAdapter,applyProfile:applyProfile,close:close});
})(typeof globalThis!=='undefined'?globalThis:window);
