/* QiblaAstro — Prayer schedule location + authenticated Android sync. */
(function(root){
'use strict';
var lastKey='',timer=0,TOKEN_KEY='qiblaastro:native-token';
function captureToken(){try{var hash=String(root.location.hash||'').replace(/^#/,'');var hp=new URLSearchParams(hash),t=hp.get('nativeToken');if(t&&t.length>=32){root.sessionStorage.setItem(TOKEN_KEY,t);hp.delete('nativeToken');var cleanHash=hp.toString();root.history.replaceState(null,'',root.location.pathname+root.location.search+(cleanHash?'#'+cleanHash:''));return t;}return root.sessionStorage.getItem(TOKEN_KEY)||'';}catch(_){return '';}}
function currentKey(){try{if(!Number.isFinite(Number(LAT))||!Number.isFinite(Number(LON)))return '';var src=typeof gnssSource!=='undefined'?String(gnssSource):'unknown';return Number(LAT).toFixed(3)+','+Number(LON).toFixed(3)+'|'+src;}catch(e){return '';}}
function invalidateIfNeeded(){var key=currentKey();if(!key)return;if(!lastKey){lastKey=key;return;}if(key===lastKey)return;lastKey=key;try{if(typeof pKey!=='undefined')pKey='';}catch(e){}try{if(root.QiblaPrayerScreen&&typeof root.QiblaPrayerScreen.render==='function')root.QiblaPrayerScreen.render();}catch(e){}try{root.dispatchEvent(new CustomEvent('qiblaastro:prayer-location-changed',{detail:{key:key}}));}catch(e){}}
function minuteFor(name){try{var p=(typeof pCache!=='undefined'&&Array.isArray(pCache))?pCache.find(function(x){return x&&x.n===name;}):null;if(!p||!Number.isFinite(Number(p.h)))return -1;return ((Math.round(Number(p.h)*60)%1440)+1440)%1440;}catch(_){return -1;}}
function nativeSync(){var token=captureToken();if(!token)return false;var loc=root.QiblaPrayerLocation&&root.QiblaPrayerLocation.effective?root.QiblaPrayerLocation.effective():null,st=root.QiblaAdhanUI&&root.QiblaAdhanUI.getState?root.QiblaAdhanUI.getState():null;if(!loc||!st)return false;var q=new URLSearchParams();q.set('token',token);q.set('notify',st.enabled?'1':'0');q.set('city',loc.label||'');q.set('tz',loc.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone||'');var h=root.document&&root.document.getElementById('pr-h');q.set('hijri',h&&h.textContent?h.textContent:'');try{if(Number.isFinite(Number(QT)))q.set('qibla',Number(QT).toFixed(1));}catch(_){}q.set('advance',String(st.advance||0));q.set('profile',st.profile||'makkah');var map={fajr:'الفجر',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء'};Object.keys(map).forEach(function(id){q.set('t_'+id,String(minuteFor(map[id])));q.set('m_'+id,(st.prayers&&st.prayers[map[id]])||'off');});var uri='intent://prayer-sync?'+q.toString()+'#Intent;scheme=qiblaastro;package=com.qiblalabs;end';try{(root.top||root).location.href=uri;return true;}catch(_){try{root.location.href=uri;return true;}catch(__){return false;}}}
function start(){if(timer)return;captureToken();lastKey=currentKey();timer=root.setInterval(invalidateIfNeeded,1500);root.addEventListener('focus',invalidateIfNeeded);root.document&&root.document.addEventListener('visibilitychange',function(){if(!root.document.hidden)invalidateIfNeeded();});if(root.document)root.document.addEventListener('click',function(e){var t=e.target&&e.target.closest?e.target.closest('[data-city-id],[data-location-auto],[data-custom-save],[data-method],[data-asr],[data-high-lat],[data-qa-close-sheet],[data-profile],[data-advance],[data-prayer-mode],[data-qa-adhan-toggle]'):null;if(t)try{nativeSync();}catch(_){}},false);}
root.QiblaPrayerNativeSync=Object.freeze({sync:nativeSync,captureToken:captureToken});
root.QiblaPrayerScheduleSync=Object.freeze({start:start,check:invalidateIfNeeded});
if(root.document){if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',start,{once:true});else start();}
})(typeof globalThis!=='undefined'?globalThis:window);
