/* QiblaAstro — Prayer Day Journey Presenter
 * Presentation only. HTML lives in pages/prayer.html.
 * Reads prayer cache and prayer-only location state; never calculates prayer times.
 */
(function(root){'use strict';var timer=0,mounted=false;
function svg(body){return '<svg class="qa-prayer-svg" viewBox="0 0 32 32" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+body+'</svg>';}
var icons={'الفجر':svg('<path d="M7 23h18"/><path d="M10 23a6 6 0 0 1 12 0"/><path d="M16 5v3M8.8 8.5l2 2M23.2 8.5l-2 2"/><path d="M5 16h3M24 16h3"/>'),'الشروق':svg('<path d="M6 24h20"/><path d="M9 22a7 7 0 0 1 14 0"/><path d="M16 5v4M7.5 9.5l3 3M24.5 9.5l-3 3M5 17h4M23 17h4"/>'),'الظهر':svg('<circle cx="16" cy="16" r="5"/><path d="M16 3v5M16 24v5M3 16h5M24 16h5M6.8 6.8l3.5 3.5M21.7 21.7l3.5 3.5M25.2 6.8l-3.5 3.5M10.3 21.7l-3.5 3.5"/>'),'العصر':svg('<path d="M7 23h18"/><path d="M10 21a5 5 0 0 1 9-3 4.5 4.5 0 0 1 6 4"/><circle cx="10" cy="10" r="3.5"/><path d="M10 4v2M4 10h2M14 6l1.5-1.5"/>'),'المغرب':svg('<path d="M6 23h20"/><path d="M10 23a6 6 0 0 1 12 0"/><path d="M16 6v3M8.5 10l2 2M23.5 10l-2 2M5 17h3M24 17h3"/><path d="M11 27h10"/>'),'العشاء':svg('<path d="M20.5 6.5a8 8 0 1 0 5 12.5 7 7 0 0 1-5-12.5z"/><path d="M9 7l.7 1.6L11 9.3l-1.3.7L9 11.6 8.3 10 7 9.3l1.3-.7L9 7zM24 8l.5 1.1 1 .5-1 .5L24 11.2l-.5-1.1-1-.5 1-.5L24 8z"/>')};
function bellSvg(mode){if(mode==='off')return svg('<path d="M10 13a6 6 0 0 1 12 0v5l2 3H8l2-3v-5"/><path d="M13 24h6"/><path d="M7 7l18 18"/>');if(mode==='notification')return svg('<circle cx="16" cy="16" r="7"/><circle cx="16" cy="16" r="2"/>');return svg('<path d="M10 13a6 6 0 0 1 12 0v5l2 3H8l2-3v-5"/><path d="M13 24h6M16 6V4"/>');}
function byId(id){return root.document&&root.document.getElementById(id);}function fmt(h){try{if(root.QiblaPrayerTimeFormat&&root.QiblaPrayerTimeFormat.format12)return root.QiblaPrayerTimeFormat.format12(h);return typeof hm==='function'?hm(h):'--:--';}catch(e){return'--:--';}}function fmtCountdown(sec){try{return typeof shms==='function'?shms(sec):'--:--:--';}catch(e){return'--:--:--';}}function getCache(){try{return(typeof pCache!=='undefined'&&Array.isArray(pCache))?pCache:null;}catch(e){return null;}}
function ensureLocationResolver(){if(root.QiblaLocationLabel)return Promise.resolve(root.QiblaLocationLabel);return new Promise(function(resolve){var old=root.document.querySelector('script[data-qibla-location-label]');if(old){old.addEventListener('load',function(){resolve(root.QiblaLocationLabel||null);},{once:true});return;}var s=root.document.createElement('script');s.src='js/presentation/location-label.js?v=20260814-prayer-location2';s.async=false;s.setAttribute('data-qibla-location-label','true');s.onload=function(){resolve(root.QiblaLocationLabel||null);};s.onerror=function(){resolve(null);};(root.document.head||root.document.documentElement).appendChild(s);});}
function effectiveLocation(){try{return root.QiblaPrayerLocation&&root.QiblaPrayerLocation.effective?root.QiblaPrayerLocation.effective():null;}catch(e){return null;}}
function cityLabel(){var pl=effectiveLocation();if(pl&&pl.mode==='manual')return pl.label;try{var api=root.QiblaLocationLabel;if(api&&typeof api.getLabel==='function'){var s=String(api.getLabel()||'').trim();if(s&&s.indexOf('GPS')===-1&&s.indexOf('IP')===-1&&s!=='الموقع الافتراضي')return s;}}catch(e){}var el=byId('prayer-location-label');return el?String(el.textContent||'').trim():'';}
function sourceLabel(){var pl=effectiveLocation();if(pl&&pl.mode==='manual')return'يدوي · '+pl.label;var city=cityLabel();if(city)return city;return'موقعك الحالي · GPS';}
function hijri(now){try{return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric'}).format(now)+' هـ';}catch(e){return'';}}function greg(now){try{return new Intl.DateTimeFormat('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now);}catch(e){return'';}}
function bindStaticUi(){if(root.QiblaAdhanUI&&typeof root.QiblaAdhanUI.bind==='function')root.QiblaAdhanUI.bind(byId('qa-adhan-card'));var table=byId('qa-prayer-table');if(table&&!table.dataset.alertBound){table.dataset.alertBound='1';table.addEventListener('click',function(e){var b=e.target.closest('[data-prayer-alert]');if(!b||!root.QiblaAdhanUI)return;var name=b.getAttribute('data-prayer-alert');if(name==='الشروق')return;root.QiblaAdhanUI.openPrayer(name);});}}
function normalizedSpan(start,end){var span=end-start;return span<=0?span+24:span;}function calcPosition(pr,h){if(!pr||pr.length<2)return 0;var start=pr[0].h,end=pr[pr.length-1].h,span=normalizedSpan(start,end),x=h-start;if(x<0)x=0;if(x>span)x=span;return Math.max(0,Math.min(100,x/span*100));}
function bell(name){if(name==='الشروق')return{icon:svg('<path d="M7 22h18"/><path d="M10 21a6 6 0 0 1 12 0"/><path d="M16 7v3M8 12l2 2M24 12l-2 2"/>'),cls:' sun',label:'الشروق'};var mode=root.QiblaAdhanUI?root.QiblaAdhanUI.getPrayerMode(name):'adhan';return mode==='adhan'?{icon:bellSvg('adhan'),cls:' mode-adhan',label:'أذان'}:mode==='notification'?{icon:bellSvg('notification'),cls:' mode-notification',label:'إشعار'}:{icon:bellSvg('off'),cls:' mode-off',label:'بدون تنبيه'};}
function renderTrack(pr,ni){var host=byId('qa-day-track-labels');if(!host)return;host.innerHTML=pr.map(function(p,i){return'<span class="qa-track-item'+(i===ni?' active':'')+'"><b>'+p.n+'</b><small>'+fmt(p.h)+'</small></span>';}).join('');}
function currentCivilHour(now){var l=effectiveLocation();try{if(l&&root.QiblaPrayerLocation&&root.QiblaPrayerLocation.civilHour)return root.QiblaPrayerLocation.civilHour(now,l.timeZone);}catch(e){}return now.getHours()+now.getMinutes()/60+now.getSeconds()/3600;}
function render(){var page=byId('page-prayer');if(!page||!byId('qa-prayer-table'))return;var pr=getCache();if(!pr||!pr.length)return;var now=new Date(),h=currentCivilHour(now),ci=-1;for(var i=pr.length-1;i>=0;i--){if(h>=pr[i].h){ci=i;break;}}var ni=(ci+1)%pr.length,np=pr[ni],secs=(np.h-h)*3600;if(secs<0)secs+=86400;var n=byId('qa-next-name'),t=byId('qa-next-time'),cd=byId('qa-next-countdown');if(n)n.textContent=np.n;if(t)t.textContent=fmt(np.h);if(cd)cd.textContent=fmtCountdown(secs);var date=byId('qa-prayer-date');if(date)date.textContent=greg(now)+' · '+hijri(now);var hs=byId('qa-hijri');if(hs)hs.textContent=hijri(now);var src=sourceLabel(),srcEl=byId('qa-prayer-source');if(srcEl)srcEl.textContent=src;var mainLoc=byId('prayer-location-label');if(mainLoc)mainLoc.textContent=cityLabel()||src;var srcD=byId('qa-location-source-detail');if(srcD)srcD.textContent=src;
var table=byId('qa-prayer-table');if(table){table.innerHTML=pr.map(function(p,i){var next=i===ni,past=!next&&ci>=0&&i<=ci,sub=p.n==='الشروق'?'الشروق':next?'الصلاة القادمة':past?'انتهى وقتها':'اليوم',bl=bell(p.n);return'<div class="qa-prayer-row'+(next?' next':past?' past':'')+'"><div class="qa-prayer-icon '+(next?'active':'')+'">'+(icons[p.n]||svg('<circle cx="16" cy="16" r="6"/>'))+'</div><div class="qa-prayer-name">'+p.n+'<small>'+sub+'</small></div><div class="qa-prayer-time">'+fmt(p.h)+'</div><button class="qa-prayer-bell'+bl.cls+'" type="button" '+(p.n==='الشروق'?'disabled':'data-prayer-alert="'+p.n+'"')+' aria-label="'+bl.label+' '+p.n+'">'+bl.icon+'</button></div>';}).join('');}
renderTrack(pr,ni);var pos=calcPosition(pr,h),progress=byId('qa-day-progress'),dot=byId('qa-day-now');if(progress)progress.style.width=(pos*.9).toFixed(1)+'%';if(dot)dot.style.right=(5+pos*.9).toFixed(1)+'%';if(root.QiblaAdhanUI)root.QiblaAdhanUI.sync(byId('qa-adhan-card'));}
function mount(){if(mounted)return true;var page=byId('page-prayer');if(!page||!byId('qa-prayer-table'))return false;page.classList.add('qa-prayer-screen');page.removeAttribute('aria-busy');page.setAttribute('data-presentation-ready','true');mounted=true;bindStaticUi();ensureLocationResolver().then(function(api){if(api&&typeof api.update==='function')api.update();render();});render();timer=root.setInterval(render,1000);return true;}function stop(){if(timer){root.clearInterval(timer);timer=0;}mounted=false;}root.addEventListener('qiblaastro:location-label',render);root.addEventListener('qiblaastro:prayer-location-change',render);root.QiblaPrayerScreen=Object.freeze({mount:mount,render:render,stop:stop});})(typeof globalThis!=='undefined'?globalThis:window);
