/* Serenity Quran streaming controller — presentation/audio only */
(function(root){'use strict';
var API_R='https://www.mp3quran.net/api/v3/reciters?language=ar',API_S='https://www.mp3quran.net/api/v3/suwar?language=ar',CACHE='mizan-serenity-mp3quran-v3',STATE='mizan-serenity-state-v1',FAV='mizan-serenity-favorites-v1',RECENT='mizan-serenity-recent-v1';
var FEATURED=['عبد الباسط','الحصري','المنشاوي','مصطفى اسماعيل','محمد رفعت','مشاري','العفاسي','ماهر المعيقلي','السديس','سعود الشريم','ياسر الدوسري','خالد الجليل'];
var reciters=[],suwar=[],reciter=null,moshaf=null,surah=null,mounted=false,sleepUntil=0,stopAtEnd=false,sleepTick=0,lastPersist=0;
function d(){return root.document}function id(x){return d().getElementById(x)}function norm(v){return String(v||'').normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').toLowerCase().trim()}function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function time(s){if(!isFinite(s)||s<0)return'0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}function json(k,f){try{return JSON.parse(root.localStorage.getItem(k)||'null')||f}catch(_){return f}}function put(k,v){try{root.localStorage.setItem(k,JSON.stringify(v))}catch(_){}}
function mlist(r){return(r&&Array.isArray(r.moshaf)?r.moshaf:[]).filter(function(m){return m&&m.server&&m.surah_list})}function aset(m){return new Set(String(m&&m.surah_list||'').split(',').map(Number).filter(Boolean))}function rank(r){var n=norm(r.name),i=FEATURED.findIndex(function(x){return n.indexOf(norm(x))!==-1});return i<0?999:i}function ordered(a){return a.slice().sort(function(x,y){var a=rank(x),b=rank(y);return a!==b?a-b:String(x.name).localeCompare(String(y.name),'ar')})}
function saveCache(){put(CACHE,{reciters:reciters,suwar:suwar})}function cached(){var x=json(CACHE,null);if(x&&x.reciters&&x.suwar){reciters=x.reciters;suwar=x.suwar;return true}return false}function offline(){var e=id('sr-offline');if(e)e.classList.toggle('show',root.navigator&&root.navigator.onLine===false)}
async function load(){offline();var g=id('sr-reciter-grid');if(g)g.innerHTML='<div class="sr-status">يتم الاتصال بمكتبة التلاوات…</div>';try{var a=await Promise.all([root.fetch(API_R,{cache:'no-store'}),root.fetch(API_S,{cache:'no-store'})]);if(!a[0].ok||!a[1].ok)throw 0;var p=await Promise.all([a[0].json(),a[1].json()]);reciters=(p[0].reciters||[]).filter(function(r){return mlist(r).length});suwar=p[1].suwar||[];saveCache();renderReciters();restore()}catch(_){if(cached()){renderReciters();restore()}else if(g)g.innerHTML='<div class="sr-status">تعذر تحميل القرّاء.<br><button class="sr-retry" id="sr-retry">إعادة المحاولة</button></div>';var b=id('sr-retry');if(b)b.onclick=load}}
function label(m){return String(m&&m.name||'تلاوة القرآن الكريم').trim()}function meta(m){var r=String(m&&(m.rewaya||m.riwaya)||'').trim(),x=[];if(r&&norm(r)!==norm(label(m)))x.push(r);x.push((m.surah_total||aset(m).size||'—')+' سورة');return x.join(' · ')}function key(){return reciter&&moshaf&&surah?[reciter.id,label(moshaf),surah].join('|'):''}function snapshot(pos){var s=suwar.find(function(x){return+x.id===+surah});return reciter&&moshaf&&s?{reciterId:+reciter.id,reciter:reciter.name,edition:label(moshaf),surah:+surah,surahName:s.name,pos:+pos||0,at:Date.now()}:null}
function openSheet(name){if(name==='edition'&&!reciter)return;if(name==='surah'&&!moshaf)return;closeSheet();var s=id('sr-'+name+'-sheet'),b=id('sr-sheet-backdrop');if(s)s.hidden=false;if(b)b.hidden=false;d().documentElement.classList.add('sr-sheet-open');if(name==='reciter')renderReciters();if(name==='edition')renderEditions();if(name==='surah')renderSuwar();if(name==='library')renderLibrary('favs')}
function closeSheet(){['reciter','edition','surah','library','sleep'].forEach(function(n){var s=id('sr-'+n+'-sheet');if(s)s.hidden=true});var b=id('sr-sheet-backdrop');if(b)b.hidden=true;d().documentElement.classList.remove('sr-sheet-open')}
function steps(){var a=id('sr-step-reciter'),b=id('sr-step-edition'),c=id('sr-step-surah');[a,b,c].forEach(function(x){if(x)x.classList.remove('active','done')});if(!reciter){a&&a.classList.add('active')}else{a&&a.classList.add('done');if(!moshaf)b&&b.classList.add('active');else{b&&b.classList.add('done');c&&c.classList.add(surah?'done':'active')}}}
function renderReciters(){var g=id('sr-reciter-grid'),q=norm(id('sr-reciter-search')&&id('sr-reciter-search').value),count=id('sk-track-list');if(!g)return;var list=ordered(reciters).filter(function(r){return!q||norm(r.name).indexOf(q)!==-1});if(count)count.textContent=reciters.length+' قارئًا متاحًا';g.innerHTML=list.map(function(r){var n=mlist(r).length;return'<button class="sr-reciter-card'+(reciter&&+reciter.id===+r.id?' active':'')+'" data-r="'+r.id+'"><strong>'+esc(r.name)+'</strong><small>'+n+' '+(n>1?'خيارات تلاوة ورواية':'تلاوة متاحة')+'</small></button>'}).join('')||'<div class="sr-status">لا توجد نتائج</div>';g.querySelectorAll('[data-r]').forEach(function(b){b.onclick=function(){selectReciter(+b.dataset.r)}})}
function selectReciter(n){reciter=reciters.find(function(r){return+r.id===n});if(!reciter)return;moshaf=null;surah=null;id('sr-choice-reciter-name').textContent=reciter.name;id('sr-open-edition').disabled=false;id('sr-choice-edition-name').textContent='اختر الرواية';id('sr-choice-edition-meta').textContent=mlist(reciter).length+' خيارات متاحة';id('sr-open-surah').disabled=true;id('sr-choice-surah-name').textContent='اختر السورة';steps();closeSheet();root.setTimeout(function(){openSheet('edition')},120)}
function renderEditions(){var g=id('sr-edition-grid');if(!g||!reciter)return;var list=mlist(reciter);g.innerHTML=list.map(function(m,i){return'<button class="sr-edition-card'+(moshaf===m?' active':'')+'" data-e="'+i+'"><span class="sr-edition-icon">'+(i+1)+'</span><span class="sr-edition-copy"><strong>'+esc(label(m))+'</strong><small>'+esc(meta(m))+'</small></span><span class="sr-edition-count">'+(m.surah_total||aset(m).size||'—')+'</span></button>'}).join('');g.querySelectorAll('[data-e]').forEach(function(b){b.onclick=function(){selectEdition(+b.dataset.e)}})}
function selectEdition(i){moshaf=mlist(reciter)[i];if(!moshaf)return;surah=null;id('sr-choice-edition-name').textContent=label(moshaf);id('sr-choice-edition-meta').textContent=meta(moshaf);id('sr-open-surah').disabled=false;id('sr-choice-surah-name').textContent='اختر السورة';id('sr-choice-surah-meta').textContent=aset(moshaf).size+' سورة متاحة';steps();closeSheet();root.setTimeout(function(){openSheet('surah')},120)}
function renderSuwar(){var g=id('sr-surah-grid'),q=norm(id('sr-surah-search')&&id('sr-surah-search').value);if(!g||!moshaf)return;var allowed=aset(moshaf),list=suwar.filter(function(s){return allowed.has(+s.id)&&(!q||norm(s.name).indexOf(q)!==-1)});g.innerHTML=list.map(function(s){return'<button class="sr-surah-card'+(surah===+s.id?' playing':'')+'" data-s="'+s.id+'"><b>'+esc(s.name)+'</b><small>'+String(s.id).padStart(3,'0')+'</small></button>'}).join('')||'<div class="sr-status">لا توجد سورة مطابقة</div>';g.querySelectorAll('[data-s]').forEach(function(b){b.onclick=function(){play(+b.dataset.s)}})}function url(n){var b=String(moshaf.server);if(b.slice(-1)!=='/')b+='/';return b+String(n).padStart(3,'0')+'.mp3'}
function rememberRecent(pos){var x=snapshot(pos);if(!x)return;var a=json(RECENT,[]).filter(function(v){return !(v.reciterId===x.reciterId&&v.edition===x.edition&&v.surah===x.surah)});a.unshift(x);put(RECENT,a.slice(0,20));put(STATE,x)}
function play(n,pos){var s=suwar.find(function(x){return+x.id===n}),a=id('sr-audio');if(!s||!a)return;surah=n;id('sr-choice-surah-name').textContent='سورة '+s.name;id('sr-choice-surah-meta').textContent=reciter.name;id('sr-now-surah').textContent='سورة '+s.name;id('sr-now-reciter').textContent=reciter.name+' · '+label(moshaf);steps();closeSheet();a.src=url(n);a.load();a.onloadedmetadata=function(){progress();if(pos&&pos<a.duration-5)a.currentTime=pos};var p=a.play();if(p&&p.catch)p.catch(function(){});rememberRecent(pos||0);renderSuwar();favState();playBtn()}
function restore(){var x=json(STATE,null);if(!x||!reciters.length)return;var r=reciters.find(function(v){return+v.id===+x.reciterId});if(!r)return;reciter=r;var list=mlist(r),m=list.find(function(v){return label(v)===x.edition})||list[0];if(!m)return;moshaf=m;id('sr-choice-reciter-name').textContent=r.name;id('sr-open-edition').disabled=false;id('sr-choice-edition-name').textContent=label(m);id('sr-choice-edition-meta').textContent=meta(m);id('sr-open-surah').disabled=false;if(x.surah){surah=+x.surah;var s=suwar.find(function(v){return+v.id===surah});if(s){id('sr-choice-surah-name').textContent='سورة '+s.name;id('sr-choice-surah-meta').textContent=r.name;id('sr-now-surah').textContent='سورة '+s.name;id('sr-now-reciter').textContent=r.name+' · '+label(m);var a=id('sr-audio');a.src=url(surah);a.load();a.onloadedmetadata=function(){if(x.pos&&x.pos<a.duration-5)a.currentTime=x.pos;progress()}}}steps();favState()}
function favorites(){return json(FAV,[])}function favState(){var b=id('sr-fav-btn'),k=key();if(!b)return;var on=k&&favorites().some(function(v){return v.key===k});b.textContent=on?'♥':'♡';b.classList.toggle('active',!!on);b.setAttribute('aria-label',on?'إزالة من المفضلة':'إضافة إلى المفضلة')}
function toggleFav(){var x=snapshot(id('sr-audio').currentTime);if(!x)return;var k=key(),a=favorites(),i=a.findIndex(function(v){return v.key===k});if(i>=0)a.splice(i,1);else{x.key=k;a.unshift(x)}put(FAV,a.slice(0,50));favState()}
function renderLibrary(tab){var g=id('sr-library-list'),f=id('sr-tab-favs'),r=id('sr-tab-recent');if(!g)return;var a=tab==='recent'?json(RECENT,[]):favorites();f.classList.toggle('active',tab!=='recent');r.classList.toggle('active',tab==='recent');g.innerHTML=a.length?a.map(function(x,i){return'<button class="sr-library-item" data-lib="'+i+'"><strong>سورة '+esc(x.surahName)+'</strong><small>'+esc(x.reciter)+' · '+esc(x.edition)+(x.pos?' · عند '+time(x.pos):'')+'</small></button>'}).join(''):'<div class="sr-status">لا توجد عناصر محفوظة بعد</div>';g.querySelectorAll('[data-lib]').forEach(function(b){b.onclick=function(){resumeItem(a[+b.dataset.lib])}})}
function resumeItem(x){var r=reciters.find(function(v){return+v.id===+x.reciterId});if(!r)return;reciter=r;moshaf=mlist(r).find(function(v){return label(v)===x.edition})||mlist(r)[0];if(!moshaf)return;id('sr-choice-reciter-name').textContent=r.name;id('sr-open-edition').disabled=false;id('sr-choice-edition-name').textContent=label(moshaf);id('sr-choice-edition-meta').textContent=meta(moshaf);id('sr-open-surah').disabled=false;play(+x.surah,+x.pos||0)}
function adjacent(x){if(!moshaf||surah===null)return;var a=Array.from(aset(moshaf)).sort(function(a,b){return a-b}),i=a.indexOf(+surah);if(i>=0)play(a[(i+x+a.length)%a.length])}function toggle(){var a=id('sr-audio');if(!a||!a.src)return;a.paused?a.play().catch(function(){}):a.pause();playBtn()}function playBtn(){var a=id('sr-audio'),b=id('sk-play-btn');if(a&&b)b.textContent=a.paused?'▶':'❚❚'}
function persistProgress(){var a=id('sr-audio');if(!a||!surah)return;var now=Date.now();if(now-lastPersist<5000)return;lastPersist=now;var x=snapshot(a.currentTime);if(x)put(STATE,x)}function progress(){var a=id('sr-audio');if(!a)return;id('sk-current').textContent=time(a.currentTime);id('sk-duration').textContent=time(a.duration);id('sk-progress').style.width=(a.duration?Math.min(100,a.currentTime/a.duration*100):0)+'%';persistProgress()}
function timerLabel(){var e=id('sr-sleep-label');if(!e)return;if(stopAtEnd)e.textContent='نهاية السورة';else if(sleepUntil){var n=Math.max(0,Math.ceil((sleepUntil-Date.now())/60000));e.textContent=n+' د'}else e.textContent='مؤقت'}function clearTimer(){sleepUntil=0;stopAtEnd=false;if(sleepTick){root.clearInterval(sleepTick);sleepTick=0}timerLabel()}function setTimer(min){clearTimer();sleepUntil=Date.now()+min*60000;sleepTick=root.setInterval(function(){if(Date.now()>=sleepUntil){var a=id('sr-audio');a&&a.pause();clearTimer()}else timerLabel()},1000);timerLabel();closeSheet()}function endTimer(){clearTimer();stopAtEnd=true;timerLabel();closeSheet()}
function bind(){id('sr-open-reciter').onclick=function(){openSheet('reciter')};id('sr-open-edition').onclick=function(){openSheet('edition')};id('sr-open-surah').onclick=function(){openSheet('surah')};id('sr-library-btn').onclick=function(){openSheet('library')};id('sr-sleep-btn').onclick=function(){openSheet('sleep')};id('sr-fav-btn').onclick=toggleFav;id('sr-sheet-backdrop').onclick=closeSheet;d().querySelectorAll('#page-serenity [data-sr-close]').forEach(function(b){b.onclick=closeSheet});d().querySelectorAll('#page-serenity [data-sr-open]').forEach(function(b){b.onclick=function(){openSheet(b.dataset.srOpen)}});id('sr-reciter-search').oninput=renderReciters;id('sr-surah-search').oninput=renderSuwar;id('sk-play-btn').onclick=toggle;id('sr-prev-btn').onclick=function(){adjacent(-1)};id('sr-next-btn').onclick=function(){adjacent(1)};id('sr-tab-favs').onclick=function(){renderLibrary('favs')};id('sr-tab-recent').onclick=function(){renderLibrary('recent')};d().querySelectorAll('#sr-sleep-sheet [data-min]').forEach(function(b){b.onclick=function(){setTimer(+b.dataset.min)}});d().querySelector('[data-end-surah]').onclick=endTimer;d().querySelector('[data-timer-cancel]').onclick=function(){clearTimer();closeSheet()};var a=id('sr-audio');a.onplay=function(){playBtn();id('sr-now-kicker').textContent='﴿ استمع وأنصت ﴾'};a.onpause=function(){playBtn();id('sr-now-kicker').textContent='يُتلى الآن'};a.onended=function(){rememberRecent(0);if(stopAtEnd){clearTimer();return}adjacent(1)};a.ontimeupdate=progress;a.onerror=function(){id('sr-offline').classList.add('show')};var t=d().querySelector('#page-serenity .sr-progress-track');t.onclick=function(e){if(!a.duration)return;var r=t.getBoundingClientRect();a.currentTime=Math.max(0,Math.min(a.duration,(e.clientX-r.left)/r.width*a.duration))};root.addEventListener('online',offline);root.addEventListener('offline',offline);root.addEventListener('beforeunload',function(){var x=snapshot(a.currentTime);if(x)put(STATE,x)})}
function mount(){if(mounted)return true;if(!id('page-serenity')||!id('sr-reciter-grid'))return false;mounted=true;bind();steps();load();return true}root.QiblaSerenityScreen=Object.freeze({mount:mount,reload:load});
})(typeof globalThis!=='undefined'?globalThis:window);