/*
 * QiblaAstro — Guarded Presentation Page Loader
 * Loads only explicitly registered non-scientific page fragments.
 * It is intentionally NOT auto-started. Activation is per-page and explicit.
 * © 2026 محمد سيد جبر بحيرى — Mohamed SG Behairy. All Rights Reserved.
 */
(function (root) {
  'use strict';
  var FORBIDDEN = Object.freeze(['astronomical-solver','astro-verification','astronomical-verification-session','astronomical-verification-store','astronomical-observation-bridge','camera-pose','camera-projection','celestial-detector','gravity-reference','getUserMedia','MediaStream','trueCameraHeadingDeg','verificationOffsetDeg','observedQiblaBearingDeg','targetAzDeg','targetAltDeg','QiblaAstronomicalSolver']);
  function assertRegistry(){if(!root.QiblaPresentationPageRegistry)throw new Error('Presentation page registry is not loaded.');}
  function parseFragment(html,expectedRootId){var template=root.document.createElement('template');template.innerHTML=String(html||'').trim();var roots=Array.prototype.slice.call(template.content.children);if(roots.length!==1||roots[0].id!==expectedRootId)throw new Error('Fragment root contract failed for '+expectedRootId+'.');return roots[0];}
  function assertNoScientificTokens(text){var found=FORBIDDEN.filter(function(token){return text.indexOf(token)!==-1;});if(found.length)throw new Error('Presentation fragment contains protected scientific token(s): '+found.join(', '));}
  function assertRequiredIds(rootNode,requiredIds){requiredIds.forEach(function(id){if(rootNode.id===id)return;if(!rootNode.querySelector('#'+id))throw new Error('Presentation contract missing required ID: '+id);});}
  function assertNoDuplicateIds(rootNode){var seen=Object.create(null),duplicates=[],nodes=[rootNode].concat(Array.prototype.slice.call(rootNode.querySelectorAll('[id]')));nodes.forEach(function(node){if(!node.id)return;if(seen[node.id])duplicates.push(node.id);seen[node.id]=true;});if(duplicates.length)throw new Error('Duplicate IDs in presentation fragment: '+duplicates.join(', '));}
  function loadCss(hrefs){hrefs.forEach(function(href){if(root.document.querySelector('link[data-qibla-presentation-css="'+href+'"]'))return;var link=root.document.createElement('link');link.rel='stylesheet';link.href=href;link.setAttribute('data-qibla-presentation-css',href);root.document.head.appendChild(link);});}
  function setPrayerLoadingState(liveRoot){if(!liveRoot)return;liveRoot.setAttribute('data-presentation-state','loading');liveRoot.innerHTML='<div role="status" aria-live="polite" style="min-height:70vh;display:grid;place-items:center;padding:24px;text-align:center;color:#d7e3ef;background:#07111f">جاري تحميل مواقيت الصلاة…</div>';}
  function setPrayerFailureState(liveRoot,message){if(!liveRoot)return;liveRoot.setAttribute('data-presentation-state','failed');liveRoot.innerHTML='<div role="alert" style="min-height:70vh;display:grid;place-items:center;padding:24px;text-align:center;color:#d7e3ef;background:#07111f"><div><strong style="display:block;margin-bottom:8px">تعذر تحميل شاشة مواقيت الصلاة</strong><span style="display:block;opacity:.78;margin-bottom:14px">'+(message||'تحقق من الاتصال ثم أعد المحاولة.')+'</span><button type="button" data-qa-prayer-retry style="padding:9px 16px;border-radius:10px;border:1px solid rgba(255,255,255,.24);background:rgba(255,255,255,.08);color:#d7e3ef;font:inherit;cursor:pointer;">إعادة المحاولة</button></div></div>';var retry=liveRoot.querySelector('[data-qa-prayer-retry]');if(retry)retry.addEventListener('click',function(){mount('prayer').catch(function(){});},{once:true});}
  async function validate(name){assertRegistry();var spec=root.QiblaPresentationPageRegistry.get(name);if(!spec)throw new Error('Unregistered presentation page: '+name);var response=await root.fetch(spec.fragment,{cache:'no-store'});if(!response.ok)throw new Error('Failed to load '+spec.fragment+': HTTP '+response.status);var html=await response.text();assertNoScientificTokens(html);var fragmentRoot=parseFragment(html,spec.rootId);assertRequiredIds(fragmentRoot,spec.requiredIds);assertNoDuplicateIds(fragmentRoot);return Object.freeze({name:name,spec:spec,html:html,fragmentRoot:fragmentRoot});}
  async function mount(name){assertRegistry();var spec=root.QiblaPresentationPageRegistry.get(name);if(!spec)throw new Error('Unregistered presentation page: '+name);var liveRoot=root.document.getElementById(spec.rootId);if(!liveRoot)throw new Error('Live page root is missing: '+spec.rootId);if(name==='prayer')setPrayerLoadingState(liveRoot);try{var checked=await validate(name);liveRoot.innerHTML=checked.fragmentRoot.innerHTML;loadCss(checked.spec.presentationCss);liveRoot.setAttribute('data-presentation-source',checked.spec.fragment);liveRoot.setAttribute('data-presentation-state','ready');root.dispatchEvent(new CustomEvent('qiblaastro:presentation-page-mounted',{detail:{name:name,rootId:checked.spec.rootId,source:checked.spec.fragment}}));return true;}catch(error){if(name==='prayer')setPrayerFailureState(liveRoot,'تعذر الوصول إلى ملف الشاشة الحديثة أو لم يجتز فحص البنية.');throw error;}}
  root.QiblaPresentationPageLoader=Object.freeze({validate:validate,mount:mount,forbiddenTokens:FORBIDDEN});
})(typeof globalThis!=='undefined'?globalThis:window);
