'use strict';
const fs=require('fs');
const assert=require('assert');
const session=fs.readFileSync('js/astronomical-verification-session.js','utf8');
const store=fs.readFileSync('js/astronomical-verification-store.js','utf8');
const cards=fs.readFileSync('js/compass-cards.js','utf8');
const runtime=fs.readFileSync('js/qibla-card-runtime.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
assert(session.includes('observedQiblaBearingDeg:normalize360(reference)'),'Astronomical Qibla must use result.qibla.qiblaBearingDeg, not camera heading.');
assert(session.includes('trueCameraHeadingDeg:heading'),'Camera heading must remain stored separately.');
assert(session.includes("alignmentMode:'astronomical-solved-bearing'"),'Mapped result must identify solved-bearing records.');
assert(session.includes("alignmentMode: result.alignmentMode || 'astronomical-solved-bearing'"),'accept() must send the canonical store contract.');
assert(!session.includes("alignmentMode: 'qibla-axis',"),'accept() must not send the rejected legacy contract.');
assert(!store.includes('Observed Qibla is exactly the solved heading'),'Store must not force Qibla bearing to equal camera heading.');
assert(store.includes("source: 'astronomical-qibla-solved-bearing'"),'Store source must describe solved Qibla bearing.');
assert(store.includes("qiblaastro:astronomical-record"),'Store must publish an immediate record event.');
assert(!runtime.includes("qiblaastro:astronomical-record"),'Authoritative card runtime must remain a read-only polling adapter and must not own astronomical record events.');
assert(cards.includes("source: 'result.qibla.qiblaBearingDeg'"),'Card must expose the Qibla engine field path.');
assert(/const VERSION='qiblaastro-v5\.[^']+'/.test(sw),'Service worker must expose a valid QiblaAstro v5 cache generation.');
const moonHeading=102.29, qibla=136.0;
assert.notStrictEqual(moonHeading,qibla,'Fixture must distinguish Moon/camera heading from Qibla.');
require('./record-display-e2e.test.js');
console.log('ASTRONOMICAL QIBLA SEMANTIC MAPPING: PASS');
