'use strict';
const fs=require('fs'),vm=require('vm');
const pages=['prayer','quran','azkar','serenity','falaki'];
const packs=['ui-phrases.js','home-phrases.js','module-phrases.js','extra-phrases.js','prayer-phrases.js','status-phrases.js','general-phrases.js','dynamic-patterns.js','en-batch1.js','en-safe2.js','safe4-phrases.js','fr-phrases.js'];
const ctx={console,setTimeout:(fn)=>fn(),dispatchEvent:()=>{},CustomEvent:function(){}};ctx.globalThis=ctx;ctx.window=ctx;vm.createContext(ctx);
for(const name of packs)vm.runInContext(fs.readFileSync('js/i18n/'+name,'utf8'),ctx,{filename:name});
vm.runInContext(fs.readFileSync('js/i18n/internal-screen-phrases.js','utf8'),ctx,{filename:'internal-screen-phrases.js'});
function map(lang){const out=Object.assign({},ctx.MIZAN_UI_PHRASES&&ctx.MIZAN_UI_PHRASES[lang]||{},ctx.MIZAN_HOME_PHRASES&&ctx.MIZAN_HOME_PHRASES[lang]||{},ctx.MIZAN_MODULE_PHRASES&&ctx.MIZAN_MODULE_PHRASES[lang]||{},ctx.MIZAN_EXTRA_PHRASES&&ctx.MIZAN_EXTRA_PHRASES[lang]||{},ctx.MIZAN_PRAYER_PHRASES&&ctx.MIZAN_PRAYER_PHRASES[lang]||{},ctx.MIZAN_STATUS_PHRASES&&ctx.MIZAN_STATUS_PHRASES[lang]||{},ctx.MIZAN_GENERAL_PHRASES&&ctx.MIZAN_GENERAL_PHRASES[lang]||{},ctx.MIZAN_SAFE4_PHRASES&&ctx.MIZAN_SAFE4_PHRASES[lang]||{});if(lang==='en')Object.assign(out,ctx.MIZAN_EN_BATCH1_PHRASES||{},ctx.MIZAN_EN_SAFE2_PHRASES||{});if(lang==='fr')Object.assign(out,ctx.MIZAN_FR_PHRASES||{});return out;}
function dynamicList(lang){let list=[];if(ctx.MIZAN_DYNAMIC_PATTERNS&&ctx.MIZAN_DYNAMIC_PATTERNS[lang])list=list.concat(ctx.MIZAN_DYNAMIC_PATTERNS[lang]);if(ctx.MIZAN_SAFE4_DYNAMIC&&ctx.MIZAN_SAFE4_DYNAMIC[lang])list=list.concat(ctx.MIZAN_SAFE4_DYNAMIC[lang]);if(lang==='en'){if(ctx.MIZAN_EN_BATCH1_DYNAMIC)list=list.concat(ctx.MIZAN_EN_BATCH1_DYNAMIC);if(ctx.MIZAN_EN_SAFE2_DYNAMIC)list=list.concat(ctx.MIZAN_EN_SAFE2_DYNAMIC);}if(lang==='fr'&&ctx.MIZAN_FR_DYNAMIC)list=list.concat(ctx.MIZAN_FR_DYNAMIC);return list;}
function dynamicCovered(text,lang){for(const pair of dynamicList(lang)){try{if(new RegExp(pair[0]).test(text))return true;}catch(_){}}return false;}
const ignore=[/بِسْمِ اللَّهِ/,/مَن قرأ حرفًا/,/عن عبد الله بن مسعود/,/أذكار الصباح والمساء مُراجعة/,/^سبحان الله$/,/^[٠-٩0-9٪%]+$/,/^۞$/];
function cleanHtml(html){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<blockquote class="qr-hadith"[\s\S]*?<\/blockquote>/gi,' ').replace(/<div class="qr-basmala"[\s\S]*?<\/div>/gi,' ').replace(/<p id="azDhikrText"[\s\S]*?<\/p>/gi,' ');}
function tokens(html){html=cleanHtml(html);const out=new Set(),re=/>\s*([^<>]*[\u0600-\u06FF][^<>]*)\s*</g;let m;while((m=re.exec(html))){const s=m[1].replace(/\s+/g,' ').trim();if(s&&s.length<220&&!ignore.some(r=>r.test(s)))out.add(s);}const ar=/(?:aria-label|title|placeholder)="([^"]*[\u0600-\u06FF][^"]*)"/g;while((m=ar.exec(html))){const s=m[1].trim();if(s&&!ignore.some(r=>r.test(s)))out.add(s);}return [...out];}
let totalMissing=0;
for(const page of pages){const file='pages/'+page+'.html';const list=tokens(fs.readFileSync(file,'utf8'));console.log('SCREEN',page,'arabic-ui-tokens='+list.length);for(const lang of ['en','fr','id','ur']){const dict=map(lang),missing=list.filter(s=>!dict[s]&&!dynamicCovered(s,lang));totalMissing+=missing.length;console.log(' ',lang,'covered='+(list.length-missing.length)+'/'+list.length,'missing='+missing.length);for(const s of missing.slice(0,35))console.log('   MISSING',lang,JSON.stringify(s));}}
console.log('INFO internal-screen total missing language entries:',totalMissing);
if(totalMissing>0)throw new Error('Internal screen translation coverage is incomplete: '+totalMissing+' missing entries.');
console.log('PASS: internal screen translation coverage complete for audited UI text, including dynamic patterns.');
