'use strict';
const assert=require('assert');
const fs=require('fs');
const Session=require('../js/astronomical-verification-session.js');
const Store=require('../js/astronomical-verification-store.js');
const ui=fs.readFileSync('js/astronomical-observatory-ui.js','utf8');
const session=fs.readFileSync('js/astronomical-verification-session.js','utf8');
assert(!ui.includes('alignmentReady'),'Automatic capture must not be gated by pre-capture Qibla alignment.');
assert(!ui.includes('حرّك الهاتف حتى يصل الجرم إلى موضع القبلة'),'Detection UI must not show Qibla-position guidance.');
assert(ui.includes("if(this.mode==='auto'&&ratio>=1)this.requestAutoCapture()"),'Stable automatic capture trigger is missing.');
const raw={trueCameraHeadingDeg:137.39,qibla:{qiblaBearingDeg:136.04},quality:{overallScore:.82},detection:{confidence:.79},gravity:{quality:.88},celestial:{azimuthDeg:110,altitudeDeg:42}};
const mapped=Session.mapResult(raw,'moon',{latitude:31.13,longitude:30.12},'auto');
assert(mapped,'Raw solved frame must map without pre-existing alignment observation.');
assert.strictEqual(mapped.observedQiblaBearingDeg,137.39);
assert.strictEqual(mapped.referenceQiblaBearingDeg,136.04);
assert(Math.abs(mapped.verificationOffsetDeg+1.35)<1e-9);
const record=Store.createRecord(mapped);
assert(record,'Canonical store must accept mapped automatic capture.');
assert.strictEqual(record.observedQiblaBearingDeg,137.39);
assert(session.includes('observedQiblaBearingDeg: result.observedQiblaBearingDeg'),'Session must record canonical observed field.');
assert(session.includes("finally { this.stop('accepted'); }"),'Successful capture must close camera/session.');
console.log('AUTO simulation: detect -> stable -> freeze -> solve -> record -> close: PASS');
console.log('MANUAL simulation uses the same finalize/record/close path: PASS');
