'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=process.cwd(),sets=['values','values-en','values-fr','values-id','values-ur'];
function read(p){return fs.readFileSync(path.join(root,p),'utf8');}
function stringNames(xml){return new Set([...xml.matchAll(/<string\s+name="([^"]+)"/g)].map(m=>m[1]));}
const azkarRequired=['azkar_channel_name','azkar_channel_description','azkar_notification_title','azkar_start_title','azkar_start_message','azkar_start_action','azkar_stop_title','azkar_stop_message','azkar_stop_action','azkar_cancel_action','azkar_permission_required','azkar_started_toast'];
for(const set of sets){const p=`android-twa/native/azkar-reminders/res/${set}/strings.xml`;assert(fs.existsSync(p),`${p} missing`);const n=stringNames(read(p));for(const k of azkarRequired)assert(n.has(k),`${set} missing ${k}`);}
const activity=read('android-twa/native/azkar-reminders/AzkarReminderActivity.java');
const azScheduler=read('android-twa/native/azkar-reminders/AzkarReminderScheduler.java');
assert(activity.includes('NativeBridgeToken.valid'),'Azkar native bridge must require per-install token');
assert(activity.includes('POST_NOTIFICATIONS'),'Azkar Android 13 notification permission missing');
assert(activity.includes('MIN_INTERVAL_MINUTES = 5'),'Azkar native activity must honor the visible five-minute interval');
assert(activity.includes('AzkarReminderScheduler.stop(this)'),'Azkar native stop action must map directly to the scheduler');
assert(activity.includes('requestPermissionThenStart();'),'Azkar native start action must proceed directly from the authenticated toggle');
assert(azScheduler.includes('MIN_INTERVAL_MINUTES = 5'),'Azkar scheduler must honor five-minute reminders');
assert(azScheduler.includes('setAndAllowWhileIdle'),'Azkar reminders must remain locally scheduled while the app UI is closed');
assert(azScheduler.includes('PendingIntent.getBroadcast')&&azScheduler.includes('AzkarReminderReceiver.class'),'Azkar reminder must be delivered by BroadcastReceiver without an open TWA page');
const prayerRequired=['prayer_channel_adhan','prayer_channel_notice','prayer_channel_description','prayer_notification_title','prayer_notification_now','prayer_notification_advance','prayer_name_fajr','prayer_name_dhuhr','prayer_name_asr','prayer_name_maghrib','prayer_name_isha'];
const widgetRequired=['widget_app_name','widget_city_unavailable','widget_refresh_required','widget_value_unavailable','widget_qibla_unavailable','widget_qibla_value'];
for(const set of sets){let p=`android-twa/native/prayer-widget/res/${set}/strings.xml`;assert(fs.existsSync(p),`${p} missing`);let n=stringNames(read(p));for(const k of prayerRequired)assert(n.has(k),`${set} missing ${k}`);p=`android-twa/native/widget/res/${set}/strings.xml`;n=stringNames(read(p));for(const k of widgetRequired)assert(n.has(k),`${set} missing ${k}`);}
const token=read('android-twa/native/prayer-widget/NativeBridgeToken.java');
const launcher=read('android-twa/native/prayer-widget/QiblaLauncherActivity.java');
const sync=read('android-twa/native/prayer-widget/PrayerWidgetSyncActivity.java');
const scheduler=read('android-twa/native/prayer-widget/PrayerNativeScheduler.java');
const receiver=read('android-twa/native/prayer-widget/PrayerNotificationReceiver.java');
const prayerBoot=read('android-twa/native/prayer-widget/PrayerBootReceiver.java');
const widget=read('android-twa/native/widget/QiblaWidgetProvider.java');
const apply=read('android-twa/apply_native_widget.ps1');
for(const t of ['SecureRandom','MODE_PRIVATE','candidate'])assert(token.includes(t),`token gate missing ${t}`);
assert(launcher.includes('.fragment("nativeToken="'),'native token must be put in URL fragment');
assert(!launcher.includes('appendQueryParameter("nativeToken"'),'native token must never enter HTTP query');
assert(sync.includes('NativeBridgeToken.valid'),'sync activity must reject unauthenticated data');
assert(sync.includes('MODE_PRIVATE'),'sync data must use app-private storage');
assert(sync.includes('safePlan(d.getQueryParameter("plan"))'),'native prayer bridge must validate the date-stamped plan before storing it');
assert(sync.includes('days.length<2||days.length>14'),'native prayer bridge must bound the background plan horizon');
assert(scheduler.includes('setAndAllowWhileIdle'),'prayer scheduling must remain local and not require external push service');
assert(scheduler.includes('AlarmManager.RTC_WAKEUP'),'prayer alarm must be able to wake delivery while the app UI is closed');
assert(scheduler.includes('PendingIntent.getBroadcast')&&scheduler.includes('PrayerNotificationReceiver.class'),'prayer alarm must target a BroadcastReceiver rather than an open Activity/page');
assert(scheduler.includes('PRE_REQ')&&scheduler.includes('boolean pre'),'pre-prayer alert must be separate from prayer-time event');
assert(scheduler.includes('KEY_PLAN = "plan_v1"'),'date-stamped native prayer plan store is missing');
assert(scheduler.includes('nextPlannedOccurrence(plan, i, now, tz)'),'native scheduler must select the next dated prayer instead of repeating stale daily minutes');
assert(scheduler.includes('if (actual <= 0L) continue;'),'an exhausted date-stamped plan must fail closed instead of replaying stale times');
assert(receiver.includes('extends BroadcastReceiver'),'prayer delivery must remain an Android BroadcastReceiver independent of the TWA lifecycle');
assert(receiver.includes('show(context,id,mode,pre);')&&receiver.includes('PrayerNativeScheduler.reschedule(context);'),'receiver must emit the notification/adhan and then schedule the next dated event');
assert(prayerBoot.includes('ACTION_BOOT_COMPLETED')&&prayerBoot.includes('ACTION_MY_PACKAGE_REPLACED')&&prayerBoot.includes('ACTION_TIMEZONE_CHANGED')&&prayerBoot.includes('ACTION_TIME_CHANGED'),'prayer alarms must be restored after reboot/app replacement/time changes');
assert(prayerBoot.includes('PrayerNativeScheduler.reschedule(context)'),'boot/time receiver must restore the native prayer schedule');
for(const raw of ['adhan_mecca.mp3','adhan_ahmed_al_nufais.mp3','adhan_islam_sobhi.mp3','adhan_fajr.mp3'])assert(apply.includes(raw),`native Adhan package missing ${raw}`);
assert(receiver.includes('USAGE_ALARM')&&receiver.includes('rawForAdhan'),'selected local Adhan audio must play only through native prayer alarm channel');
assert(widget.includes('PrayerNativeScheduler.PREFS'),'widget must read authenticated app-private prayer store');
assert(!/android:name=["'](?:com\.qiblalabs\.)?WidgetDataActivity["']/.test(apply),'legacy WidgetDataActivity component must remain absent');
assert(apply.includes('QiblaWidgetProvider')&&apply.includes('PrayerWidgetSyncActivity'),'authenticated widget integration missing');
const plan=read('js/presentation/prayer/native-plan.js');
assert(plan.includes('QiblaPrayerMethods.calculate'),'background plan must reuse the approved prayer method engine rather than duplicate its equations');
assert(plan.includes('QiblaPrayerLocation.dateKey'),'background plan must use the effective prayer-location timezone date');
assert(plan.includes('sameMinutes(first.times,current)'),'background plan must match the live displayed schedule before it can cross the native bridge');
assert(plan.includes('Math.min(14'),'background plan horizon must remain bounded');
const webSync=read('js/presentation/prayer/schedule-sync.js');
assert(webSync.includes("TOKEN_KEY='qiblaastro:native-token'"),'web sync token storage missing');
assert(webSync.includes("AUTO_KEY='qiblaastro:prayer-native-sync-enabled:v1'"),'native prayer sync activation marker missing');
assert(webSync.includes("LAST_SYNC_KEY='qiblaastro:prayer-native-sync-last:v1'"),'native prayer sync de-duplication marker missing');
assert(webSync.includes('root.location.hash'),'web bridge must capture token from non-HTTP fragment');
assert(webSync.includes('intent://prayer-sync?'),'web prayer sync intent missing');
assert(webSync.includes("q.set('plan',payload.planText)"),'web prayer bridge must send the validated date-stamped plan');
assert(webSync.includes('QiblaPrayerNativePlan.build(14)'),'web prayer bridge must keep two weeks of dated prayer times available while the TWA is closed');
assert(webSync.includes("reason==='explicit'"),'native prayer sync must distinguish explicit user activation from automatic refresh');
assert(webSync.includes("maybeAutoSync('startup')"),'previously activated native prayer schedules must refresh when the app is opened again');
assert(webSync.includes("maybeAutoSync('location-changed')"),'native prayer schedule must refresh after trusted location changes');
assert(webSync.includes("maybeAutoSync('runtime-ready')"),'native plan must refresh only after the authoritative prayer runtime reports a valid schedule');
assert(webSync.includes('if(minute<0)return null'),'native prayer sync must fail closed until all five prayer times exist');
const azWeb=read('js/azkar-native-reminders.js');
const azPage=read('pages/azkar.html');
const azHost=read('js/presentation/azkar/host.js');
assert(azWeb.includes("token='+encodeURIComponent(token)"),'Azkar web bridge must send authenticated token');
assert(azWeb.includes('tokenFromHash'),'Azkar bridge must read token from fragment');
assert(azWeb.includes('tokenFromStorage'),'Azkar bridge must recover the authenticated token from the same-origin TWA session');
assert(azWeb.includes('Math.max(5,n)'),'Azkar web bridge must honor the visible five-minute interval');
assert(azWeb.includes("var launched=launch('start'"),'Azkar UI must inspect native launch result before persisting running state');
assert(azWeb.includes('if(!launched){clearStaleState();return;}'),'Azkar UI must fail closed without showing a false Android error note');
assert(azWeb.indexOf("var launched=launch('start'")<azWeb.indexOf('writeState(state);setUi(true,state);'),'Azkar UI must not claim a running native reminder before attempting Android launch');
assert(azWeb.includes("'qiblaastro://azkar-reminder?token='"),'Azkar bridge must use the published native custom scheme as its primary handoff');
assert(azWeb.includes('topWin.location.href=uri'),'Azkar custom-scheme handoff must remain synchronous in the trusted user click');
assert(azWeb.includes("'intent://azkar-reminder?token='"),'Azkar bridge must retain an Android intent fallback');
assert(azWeb.includes('category=android.intent.category.BROWSABLE'),'Azkar fallback intent must explicitly remain browser-invokable');
assert(!azWeb.includes('a.click()'),'Azkar native handoff must not rely on a synthetic hidden-anchor click');
assert(!azWeb.includes('تعذر بدء تنبيه Android')&&!azWeb.includes('افتح التطبيق من نسخة Android'),'obsolete visible Android failure note must remain removed');
assert(azHost.includes("TOKEN_KEY='qiblaastro:native-token'")&&azHost.includes("'?twa=1'")&&azHost.includes("'#nativeToken='+encodeURIComponent(token)"),'Azkar iframe host must propagate authenticated TWA context into the standalone page');
assert(azHost.includes('seedFrameContext(frame)'),'Azkar iframe must receive same-origin session TWA/token context after load');
assert(azPage.includes('#azAudio .az-audio-status{display:none!important}'),'Azkar audio status note must remain hidden; the toggle is the visible state control');
assert(azPage.includes('azkar-native-reminders.js?v=20260817-native4'),'Azkar page must load the latest direct-native reminder bridge');
const bootstrap=read('js/presentation/bootstrap.js');
assert(bootstrap.includes('schedule-sync.js?v=20260814-nativebridge1'),'authenticated prayer sync loader version missing');
const sw=read('service-worker.js');
assert(/qiblaastro-v\d+\.\d+-/.test(sw),'versioned service-worker cache missing');
assert(sw.includes('qiblaastro-v6.16-azkar-direct-native'),'latest direct Azkar native bridge service-worker version missing');
assert(sw.includes('./js/presentation/prayer/native-plan.js')&&sw.includes('./js/presentation/prayer/schedule-sync.js')&&sw.includes('./js/azkar-native-reminders.js'),'native web bridge files must remain in critical offline cache');
console.log('Native Android localization/security gate: PASS');
console.log('Prayer actual-time + separate pre-alert + local Adhan audio: PASS');
console.log('Prayer CLOSED-APP native chain (RTC_WAKEUP -> BroadcastReceiver -> local alarm sound -> reschedule): PASS');
console.log('Prayer reboot/app-replacement/time-change schedule restoration: PASS');
console.log('Prayer native sync refreshes only after explicit/persisted activation and fails closed before a complete schedule: PASS');
console.log('Prayer native bridge carries a validated 14-day date-stamped schedule and never replays an exhausted plan: PASS');
console.log('Azkar published-native-compatible iframe token propagation + direct custom-scheme user-gesture handoff: PASS');
console.log('Azkar native toggle + five-minute local background scheduling: PASS');
console.log('Prayer notifications AR/EN/FR/ID/UR: PASS');
console.log('Widget AR/EN/FR/ID/UR: PASS');
console.log('Per-install fragment token + MODE_PRIVATE store; legacy WidgetDataActivity absent: PASS');
