'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync('js/prayer/calculation-methods.js','utf8');
const sandbox={console,Intl,Date,Math,setInterval(){},clearInterval(){}};sandbox.globalThis=sandbox;sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(src,sandbox);
const api=sandbox.QiblaPrayerMethods;assert(api);
assert.strictEqual(api.methods.egyptian.fajrAngle,19.5);assert.strictEqual(api.methods.egyptian.ishaAngle,17.5);
assert.strictEqual(api.methods.mwl.fajrAngle,18);assert.strictEqual(api.methods.mwl.ishaAngle,17);
assert.strictEqual(api.methods.karachi.fajrAngle,18);assert.strictEqual(api.methods.karachi.ishaAngle,18);
assert.strictEqual(api.methods.isna.fajrAngle,15);assert.strictEqual(api.methods.isna.ishaAngle,15);
assert.strictEqual(api.methods.ummAlQura.fajrAngle,18.5);assert.strictEqual(api.methods.ummAlQura.ishaInterval,90);
assert.strictEqual(api.methods.singapore.fajrAngle,20);assert.strictEqual(api.methods.singapore.ishaAngle,18);
assert.strictEqual(api.recommend(30.0444,31.2357),'egyptian');assert.strictEqual(api.recommend(21.4225,39.8262),'ummAlQura');assert.strictEqual(api.recommend(24.8607,67.0011),'karachi');assert.strictEqual(api.recommend(-6.2088,106.8456),'singapore');assert.strictEqual(api.recommend(40.7128,-74.0060),'isna');assert.strictEqual(api.recommend(51.5074,-0.1278),'mwl');
const ev={rH:6,nH:12,sH:18,dec:10};
const std=api.calculate(ev,30,{method:'egyptian',lon:31,asr:'standard',highLatitude:'auto'},new Date('2026-08-14T12:00:00Z'));
const han=api.calculate(ev,30,{method:'egyptian',lon:31,asr:'hanafi',highLatitude:'auto'},new Date('2026-08-14T12:00:00Z'));
assert(std&&han);assert.strictEqual(std.prayers.find(p=>p.n==='الظهر').h,12,'Dhuhr must equal solar noon unless an explicit user adjustment exists');assert.strictEqual(std.prayers.find(p=>p.n==='المغرب').h,18,'Maghrib must equal sunset unless an explicit user adjustment exists');assert.deepStrictEqual(JSON.parse(JSON.stringify(std.adjustments)),{dhuhr:0,maghrib:0});
const asrStd=std.prayers.find(p=>p.n==='العصر').h,asrHan=han.prayers.find(p=>p.n==='العصر').h;assert(asrHan>asrStd,'Hanafi Asr must be later than Standard Asr');
const egypt=api.calculate(ev,30,{method:'egyptian',lon:31,asr:'standard',highLatitude:'auto'},new Date('2026-08-14')),mwl=api.calculate(ev,30,{method:'mwl',lon:31,asr:'standard',highLatitude:'auto'},new Date('2026-08-14'));assert(egypt.prayers[0].h!==mwl.prayers[0].h,'Egyptian Fajr must differ from MWL');
const umm=api.calculate(ev,21.4,{method:'ummAlQura',lon:39.8,asr:'standard',highLatitude:'auto'},new Date('2026-08-14'));const mag=umm.prayers.find(p=>p.n==='المغرب').h,isha=umm.prayers.find(p=>p.n==='العشاء').h;let gap=(isha-mag+24)%24;assert(Math.abs(gap-1.5)<0.02,'Umm al-Qura Isha must be 90 minutes after Maghrib outside Ramadan');
const highEv={rH:4.5,nH:12.5,sH:22.2,dec:23.3};const high=api.calculate(highEv,60,{method:'mwl',lon:10,asr:'standard',highLatitude:'seventhNight'},new Date('2026-06-21'));assert(high.prayers.every(p=>Number.isFinite(p.h)),'high latitude rule must resolve finite prayer hours');
console.log('Prayer global calculation profiles gate: PASS');console.log('Verified: zero hidden Dhuhr/Maghrib offsets, regional profiles, Asr madhab and high-latitude rules');
