/* QiblaAstro 3.1.0/code 3 — independent location permission + existing native bridges
 * © 2026 Mohamed SG Behairy. All Rights Reserved. */
'use strict';
const VERSION='qiblaastro-3.1.0-code3-location-only-r1';
const BRIDGE_RELEASE='prayer-direct-20260818';
const GNSS_RELEASE='trusted-startup-recovery-20260818';
const PERMISSIONS_RELEASE='code3-location-only-20260819-r1';
const CACHE_PREFIX='qiblaastro-';
const APP_CACHE=VERSION+'-app';
const RUNTIME_CACHE=VERSION+'-runtime';
const CRITICAL_PRESENTATION=['./index.html','./js/06-navigation.js','./js/analytics/privacy-safe-screen-tracker.js','./css/07-pages.css','./css/internal-screen-chrome.css','./css/phone-acceptance-fixes.css','./css/reading-full-width-final.css','./js/presentation/bootstrap.js','./js/presentation/page-registry.js','./js/presentation/internal-screen-chrome.js','./js/home-final.js','./js/home-reference-finalizer.js','./css/home-final.css','./css/home-action-layout-233.css','./css/home-header-controls.css','./icons/hm-astronomy.png','./js/geomag/wmm2025.js','./js/geomag/wmm2025-runtime.js','./js/presentation/compass/host.js','./js/presentation/quran/host.js','./js/presentation/quran/back-history.js','./js/presentation/azkar/host.js','./js/presentation/azkar/back-history.js','./js/presentation/compass/trusted-qibla-refresh.js','./js/presentation/permissions-onboarding.js','./js/presentation/location-label.js','./js/runtime/local-timezone-adapter.js','./js/runtime/trusted-location-dependent-sync.js','./js/prayer/calculation-methods.js','./js/prayer/prayer-settings.js','./js/prayer/prayer-location.js','./js/prayer/time-format.js','./js/presentation/prayer/calculation-settings-ui.js','./js/presentation/prayer/location-settings-ui.js','./js/presentation/prayer/native-plan.js','./js/presentation/prayer/schedule-sync.js','./js/presentation/prayer/adhan-ui.js','./js/presentation/prayer/audio-readiness.js','./js/presentation/prayer/audio-finalizer.js','./js/presentation/prayer/screen.js','./css/presentation/prayer/settings-overrides.css','./css/presentation/prayer/screen.css','./css/presentation/serenity/screen.css','./css/presentation/serenity/final-polish.css','./js/presentation/falaki/host.js','./js/17-deviation.js','./js/presentation/falaki/event-times-sync.js','./js/astronomical-verification-store.js','./js/azkar-native-reminders.js','./js/i18n/english-rollout.js','./js/i18n/home-language-picker.js','./js/i18n/internal-screen-language-bridge.js','./js/i18n/internal-screen-phrases.js','./js/i18n/internal-screen-final-phrases.js','./js/i18n/prayer-phrases.js','./js/i18n/prayer-settings-complete-phrases.js','./pages/wmm2025-test.html','./pages/prayer.html','./pages/quran.html','./pages/azkar.html','./pages/serenity.html','./pages/falaki.html','./audio/adhan/mecca.mp3','./audio/adhan/ahmed-al-nufais.mp3','./audio/adhan/islam-sobhi.mp3','./audio/adhan/fajr-alafasy.mp3'];
async function precacheCritical(){const c=await caches.open(APP_CACHE);await Promise.allSettled(CRITICAL_PRESENTATION.map(async url=>{try{const r=await fetch(url,{cache:'no-store'});if(r&&r.ok)await c.put(url,r.clone());}catch(_){}}));}
async function notifyUpdated(){try{const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients)client.postMessage({type:'SW_UPDATED',version:VERSION,bridgeRelease:BRIDGE_RELEASE,gnssRelease:GNSS_RELEASE,permissionsRelease:PERMISSIONS_RELEASE});}catch(_){}}
self.addEventListener('install',event=>{event.waitUntil((async()=>{await precacheCritical();await self.skipWaiting();})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith(CACHE_PREFIX)&&!n.startsWith(VERSION)).map(n=>caches.delete(n)));await self.clients.claim();await notifyUpdated();})());});
self.addEventListener('fetch',event=>{const r=event.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==self.location.origin)return;const code=/\.(?:js|css|html)$/i.test(u.pathname)||r.mode==='navigate';if(code){event.respondWith((async()=>{try{const x=await fetch(r,{cache:'no-store'});if(x&&x.ok)(await caches.open(APP_CACHE)).put(r,x.clone());return x;}catch(_){return(await caches.match(r))||(r.mode==='navigate'?(await caches.match('./index.html')):undefined)||new Response('',{status:503});}})());return;}event.respondWith((async()=>{const c=await caches.open(RUNTIME_CACHE),old=await c.match(r);try{const x=await fetch(r);if(x&&x.ok)c.put(r,x.clone());return x;}catch(_){return old||new Response('',{status:503});}})());});
self.addEventListener('message',event=>{const d=event.data||{};if(d.type==='SKIP_WAITING')self.skipWaiting();if(d.type==='GET_VERSION'){const x={type:'SW_VERSION',version:VERSION,bridgeRelease:BRIDGE_RELEASE,gnssRelease:GNSS_RELEASE,permissionsRelease:PERMISSIONS_RELEASE};if(event.ports&&event.ports[0])event.ports[0].postMessage(x);else if(event.source)event.source.postMessage(x);}});
